// Code generated by github.com/Khan/genqlient, DO NOT EDIT.

package generator

import (
	"context"
	"time"

	"github.com/Khan/genqlient/graphql"
	"github.com/google/uuid"
)

type Callbacks struct {
	FailureURL string `json:"failureURL"`
	ReturnURL  string `json:"returnURL"`
	SuccessURL string `json:"successURL"`
}

// GetFailureURL returns Callbacks.FailureURL, and is useful for accessing the field via an interface.
func (v *Callbacks) GetFailureURL() string { return v.FailureURL }

// GetReturnURL returns Callbacks.ReturnURL, and is useful for accessing the field via an interface.
func (v *Callbacks) GetReturnURL() string { return v.ReturnURL }

// GetSuccessURL returns Callbacks.SuccessURL, and is useful for accessing the field via an interface.
func (v *Callbacks) GetSuccessURL() string { return v.SuccessURL }

type Currency string

const (
	CurrencyUsdt Currency = "USDT"
)

type CustomFieldIn struct {
	Name  string `json:"name"`
	Value string `json:"value"`
}

// GetName returns CustomFieldIn.Name, and is useful for accessing the field via an interface.
func (v *CustomFieldIn) GetName() string { return v.Name }

// GetValue returns CustomFieldIn.Value, and is useful for accessing the field via an interface.
func (v *CustomFieldIn) GetValue() string { return v.Value }

type CustomerIn struct {
	Account string `json:"account"`
	Email   string `json:"email"`
	Phone   string `json:"phone"`
}

// GetAccount returns CustomerIn.Account, and is useful for accessing the field via an interface.
func (v *CustomerIn) GetAccount() string { return v.Account }

// GetEmail returns CustomerIn.Email, and is useful for accessing the field via an interface.
func (v *CustomerIn) GetEmail() string { return v.Email }

// GetPhone returns CustomerIn.Phone, and is useful for accessing the field via an interface.
func (v *CustomerIn) GetPhone() string { return v.Phone }

// OrderCancelResponse is returned by OrderCancel on success.
type OrderCancelResponse struct {
	Order_cancel bool `json:"order_cancel"`
}

// GetOrder_cancel returns OrderCancelResponse.Order_cancel, and is useful for accessing the field via an interface.
func (v *OrderCancelResponse) GetOrder_cancel() bool { return v.Order_cancel }

type OrderCreateIn struct {
	Amount    float64   `json:"amount"`
	Callbacks Callbacks `json:"callbacks"`
	Comment   string    `json:"comment"`
	Currency  Currency  `json:"currency"`
	// unsupported yet
	CustomFields []CustomFieldIn `json:"customFields"`
	Customer     CustomerIn      `json:"customer"`
	// in null - time + 10 minutes. Format: RFC3339: 2006-01-02T15:04:05Z07:00
	ExpirationDateTime time.Time `json:"expirationDateTime"`
	PaymentSystemID    uuid.UUID `json:"paymentSystemID"`
}

// GetAmount returns OrderCreateIn.Amount, and is useful for accessing the field via an interface.
func (v *OrderCreateIn) GetAmount() float64 { return v.Amount }

// GetCallbacks returns OrderCreateIn.Callbacks, and is useful for accessing the field via an interface.
func (v *OrderCreateIn) GetCallbacks() Callbacks { return v.Callbacks }

// GetComment returns OrderCreateIn.Comment, and is useful for accessing the field via an interface.
func (v *OrderCreateIn) GetComment() string { return v.Comment }

// GetCurrency returns OrderCreateIn.Currency, and is useful for accessing the field via an interface.
func (v *OrderCreateIn) GetCurrency() Currency { return v.Currency }

// GetCustomFields returns OrderCreateIn.CustomFields, and is useful for accessing the field via an interface.
func (v *OrderCreateIn) GetCustomFields() []CustomFieldIn { return v.CustomFields }

// GetCustomer returns OrderCreateIn.Customer, and is useful for accessing the field via an interface.
func (v *OrderCreateIn) GetCustomer() CustomerIn { return v.Customer }

// GetExpirationDateTime returns OrderCreateIn.ExpirationDateTime, and is useful for accessing the field via an interface.
func (v *OrderCreateIn) GetExpirationDateTime() time.Time { return v.ExpirationDateTime }

// GetPaymentSystemID returns OrderCreateIn.PaymentSystemID, and is useful for accessing the field via an interface.
func (v *OrderCreateIn) GetPaymentSystemID() uuid.UUID { return v.PaymentSystemID }

// OrderCreateOrder_createOrderCreate includes the requested fields of the GraphQL type OrderCreate.
type OrderCreateOrder_createOrderCreate struct {
	BillId uuid.UUID `json:"billId"`
	Url    string    `json:"url"`
}

// GetBillId returns OrderCreateOrder_createOrderCreate.BillId, and is useful for accessing the field via an interface.
func (v *OrderCreateOrder_createOrderCreate) GetBillId() uuid.UUID { return v.BillId }

// GetUrl returns OrderCreateOrder_createOrderCreate.Url, and is useful for accessing the field via an interface.
func (v *OrderCreateOrder_createOrderCreate) GetUrl() string { return v.Url }

// OrderCreateResponse is returned by OrderCreate on success.
type OrderCreateResponse struct {
	Order_create OrderCreateOrder_createOrderCreate `json:"order_create"`
}

// GetOrder_create returns OrderCreateResponse.Order_create, and is useful for accessing the field via an interface.
func (v *OrderCreateResponse) GetOrder_create() OrderCreateOrder_createOrderCreate {
	return v.Order_create
}

// OrderInfoOrder_infoOrder includes the requested fields of the GraphQL type Order.
type OrderInfoOrder_infoOrder struct {
	Amount             float64                                           `json:"amount"`
	AmountPaid         float64                                           `json:"amountPaid"`
	BillId             uuid.UUID                                         `json:"billId"`
	ChangedDateTime    time.Time                                         `json:"changedDateTime"`
	Comment            string                                            `json:"comment"`
	CreationDateTime   time.Time                                         `json:"creationDateTime"`
	Currency           Currency                                          `json:"currency"`
	CustomFields       []OrderInfoOrder_infoOrderCustomFieldsCustomField `json:"customFields"`
	Customer           OrderInfoOrder_infoOrderCustomer                  `json:"customer"`
	ExpirationDateTime time.Time                                         `json:"expirationDateTime"`
	MerchantId         uuid.UUID                                         `json:"merchantId"`
	PayUrl             string                                            `json:"payUrl"`
	PaymentSystemID    uuid.UUID                                         `json:"paymentSystemID"`
	Status             OrderStatus                                       `json:"status"`
}

// GetAmount returns OrderInfoOrder_infoOrder.Amount, and is useful for accessing the field via an interface.
func (v *OrderInfoOrder_infoOrder) GetAmount() float64 { return v.Amount }

// GetAmountPaid returns OrderInfoOrder_infoOrder.AmountPaid, and is useful for accessing the field via an interface.
func (v *OrderInfoOrder_infoOrder) GetAmountPaid() float64 { return v.AmountPaid }

// GetBillId returns OrderInfoOrder_infoOrder.BillId, and is useful for accessing the field via an interface.
func (v *OrderInfoOrder_infoOrder) GetBillId() uuid.UUID { return v.BillId }

// GetChangedDateTime returns OrderInfoOrder_infoOrder.ChangedDateTime, and is useful for accessing the field via an interface.
func (v *OrderInfoOrder_infoOrder) GetChangedDateTime() time.Time { return v.ChangedDateTime }

// GetComment returns OrderInfoOrder_infoOrder.Comment, and is useful for accessing the field via an interface.
func (v *OrderInfoOrder_infoOrder) GetComment() string { return v.Comment }

// GetCreationDateTime returns OrderInfoOrder_infoOrder.CreationDateTime, and is useful for accessing the field via an interface.
func (v *OrderInfoOrder_infoOrder) GetCreationDateTime() time.Time { return v.CreationDateTime }

// GetCurrency returns OrderInfoOrder_infoOrder.Currency, and is useful for accessing the field via an interface.
func (v *OrderInfoOrder_infoOrder) GetCurrency() Currency { return v.Currency }

// GetCustomFields returns OrderInfoOrder_infoOrder.CustomFields, and is useful for accessing the field via an interface.
func (v *OrderInfoOrder_infoOrder) GetCustomFields() []OrderInfoOrder_infoOrderCustomFieldsCustomField {
	return v.CustomFields
}

// GetCustomer returns OrderInfoOrder_infoOrder.Customer, and is useful for accessing the field via an interface.
func (v *OrderInfoOrder_infoOrder) GetCustomer() OrderInfoOrder_infoOrderCustomer { return v.Customer }

// GetExpirationDateTime returns OrderInfoOrder_infoOrder.ExpirationDateTime, and is useful for accessing the field via an interface.
func (v *OrderInfoOrder_infoOrder) GetExpirationDateTime() time.Time { return v.ExpirationDateTime }

// GetMerchantId returns OrderInfoOrder_infoOrder.MerchantId, and is useful for accessing the field via an interface.
func (v *OrderInfoOrder_infoOrder) GetMerchantId() uuid.UUID { return v.MerchantId }

// GetPayUrl returns OrderInfoOrder_infoOrder.PayUrl, and is useful for accessing the field via an interface.
func (v *OrderInfoOrder_infoOrder) GetPayUrl() string { return v.PayUrl }

// GetPaymentSystemID returns OrderInfoOrder_infoOrder.PaymentSystemID, and is useful for accessing the field via an interface.
func (v *OrderInfoOrder_infoOrder) GetPaymentSystemID() uuid.UUID { return v.PaymentSystemID }

// GetStatus returns OrderInfoOrder_infoOrder.Status, and is useful for accessing the field via an interface.
func (v *OrderInfoOrder_infoOrder) GetStatus() OrderStatus { return v.Status }

// OrderInfoOrder_infoOrderCustomFieldsCustomField includes the requested fields of the GraphQL type CustomField.
type OrderInfoOrder_infoOrderCustomFieldsCustomField struct {
	Name  string `json:"name"`
	Value string `json:"value"`
}

// GetName returns OrderInfoOrder_infoOrderCustomFieldsCustomField.Name, and is useful for accessing the field via an interface.
func (v *OrderInfoOrder_infoOrderCustomFieldsCustomField) GetName() string { return v.Name }

// GetValue returns OrderInfoOrder_infoOrderCustomFieldsCustomField.Value, and is useful for accessing the field via an interface.
func (v *OrderInfoOrder_infoOrderCustomFieldsCustomField) GetValue() string { return v.Value }

// OrderInfoOrder_infoOrderCustomer includes the requested fields of the GraphQL type Customer.
type OrderInfoOrder_infoOrderCustomer struct {
	Account string `json:"account"`
	Email   string `json:"email"`
	Phone   string `json:"phone"`
}

// GetAccount returns OrderInfoOrder_infoOrderCustomer.Account, and is useful for accessing the field via an interface.
func (v *OrderInfoOrder_infoOrderCustomer) GetAccount() string { return v.Account }

// GetEmail returns OrderInfoOrder_infoOrderCustomer.Email, and is useful for accessing the field via an interface.
func (v *OrderInfoOrder_infoOrderCustomer) GetEmail() string { return v.Email }

// GetPhone returns OrderInfoOrder_infoOrderCustomer.Phone, and is useful for accessing the field via an interface.
func (v *OrderInfoOrder_infoOrderCustomer) GetPhone() string { return v.Phone }

// OrderInfoResponse is returned by OrderInfo on success.
type OrderInfoResponse struct {
	Order_info OrderInfoOrder_infoOrder `json:"order_info"`
}

// GetOrder_info returns OrderInfoResponse.Order_info, and is useful for accessing the field via an interface.
func (v *OrderInfoResponse) GetOrder_info() OrderInfoOrder_infoOrder { return v.Order_info }

type OrderStatus string

const (
	OrderStatusCanceled OrderStatus = "CANCELED"
	OrderStatusExpired  OrderStatus = "EXPIRED"
	OrderStatusPaid     OrderStatus = "PAID"
	OrderStatusRejected OrderStatus = "REJECTED"
	OrderStatusWaiting  OrderStatus = "WAITING"
)

// __OrderCancelInput is used internally by genqlient
type __OrderCancelInput struct {
	Id uuid.UUID `json:"id"`
}

// GetId returns __OrderCancelInput.Id, and is useful for accessing the field via an interface.
func (v *__OrderCancelInput) GetId() uuid.UUID { return v.Id }

// __OrderCreateInput is used internally by genqlient
type __OrderCreateInput struct {
	Order OrderCreateIn `json:"order"`
}

// GetOrder returns __OrderCreateInput.Order, and is useful for accessing the field via an interface.
func (v *__OrderCreateInput) GetOrder() OrderCreateIn { return v.Order }

// __OrderInfoInput is used internally by genqlient
type __OrderInfoInput struct {
	Id uuid.UUID `json:"id"`
}

// GetId returns __OrderInfoInput.Id, and is useful for accessing the field via an interface.
func (v *__OrderInfoInput) GetId() uuid.UUID { return v.Id }

// The query or mutation executed by OrderCancel.
const OrderCancel_Operation = `
mutation OrderCancel ($id: UUID!) {
	order_cancel(id: $id)
}
`

func OrderCancel(
	ctx_ context.Context,
	client_ graphql.Client,
	id uuid.UUID,
) (*OrderCancelResponse, error) {
	req_ := &graphql.Request{
		OpName: "OrderCancel",
		Query:  OrderCancel_Operation,
		Variables: &__OrderCancelInput{
			Id: id,
		},
	}
	var err_ error

	var data_ OrderCancelResponse
	resp_ := &graphql.Response{Data: &data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return &data_, err_
}

// The query or mutation executed by OrderCreate.
const OrderCreate_Operation = `
mutation OrderCreate ($order: OrderCreateIn!) {
	order_create(order: $order) {
		billId
		url
	}
}
`

func OrderCreate(
	ctx_ context.Context,
	client_ graphql.Client,
	order OrderCreateIn,
) (*OrderCreateResponse, error) {
	req_ := &graphql.Request{
		OpName: "OrderCreate",
		Query:  OrderCreate_Operation,
		Variables: &__OrderCreateInput{
			Order: order,
		},
	}
	var err_ error

	var data_ OrderCreateResponse
	resp_ := &graphql.Response{Data: &data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return &data_, err_
}

// The query or mutation executed by OrderInfo.
const OrderInfo_Operation = `
query OrderInfo ($id: UUID!) {
	order_info(id: $id) {
		amount
		amountPaid
		billId
		changedDateTime
		comment
		creationDateTime
		currency
		customFields {
			name
			value
		}
		customer {
			account
			email
			phone
		}
		expirationDateTime
		merchantId
		payUrl
		paymentSystemID
		status
	}
}
`

func OrderInfo(
	ctx_ context.Context,
	client_ graphql.Client,
	id uuid.UUID,
) (*OrderInfoResponse, error) {
	req_ := &graphql.Request{
		OpName: "OrderInfo",
		Query:  OrderInfo_Operation,
		Variables: &__OrderInfoInput{
			Id: id,
		},
	}
	var err_ error

	var data_ OrderInfoResponse
	resp_ := &graphql.Response{Data: &data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return &data_, err_
}
