// Code generated by mockery v2.38.0. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "server/internal/domain"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// DbRepository is an autogenerated mock type for the DbRepository type
type DbRepository struct {
	mock.Mock
}

// ClaimGetByCode provides a mock function with given fields: _a0, _a1
func (_m *DbRepository) ClaimGetByCode(_a0 context.Context, _a1 string) (*domain.Claim, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for ClaimGetByCode")
	}

	var r0 *domain.Claim
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Claim, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Claim); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Claim)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ComboGetAll provides a mock function with given fields: _a0
func (_m *DbRepository) ComboGetAll(_a0 context.Context) ([]*domain.Combo, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for ComboGetAll")
	}

	var r0 []*domain.Combo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*domain.Combo, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*domain.Combo); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Combo)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ComboGetByCode provides a mock function with given fields: _a0, _a1
func (_m *DbRepository) ComboGetByCode(_a0 context.Context, _a1 string) (*domain.Combo, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for ComboGetByCode")
	}

	var r0 *domain.Combo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Combo, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Combo); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Combo)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ComboIncCount provides a mock function with given fields: _a0, _a1
func (_m *DbRepository) ComboIncCount(_a0 context.Context, _a1 string) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for ComboIncCount")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ConfigGet provides a mock function with given fields: _a0
func (_m *DbRepository) ConfigGet(_a0 context.Context) (*domain.Config, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for ConfigGet")
	}

	var r0 *domain.Config
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*domain.Config, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *domain.Config); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Config)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ConfigUpdateTonLastLT provides a mock function with given fields: _a0, _a1
func (_m *DbRepository) ConfigUpdateTonLastLT(_a0 context.Context, _a1 uint64) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for ConfigUpdateTonLastLT")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DepositCreate provides a mock function with given fields: _a0, _a1
func (_m *DbRepository) DepositCreate(_a0 context.Context, _a1 *domain.Deposit) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for DepositCreate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Deposit) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DepositGetByUID provides a mock function with given fields: _a0, _a1
func (_m *DbRepository) DepositGetByUID(_a0 context.Context, _a1 string) (*domain.Deposit, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for DepositGetByUID")
	}

	var r0 *domain.Deposit
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Deposit, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Deposit); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Deposit)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DepositUpdate provides a mock function with given fields: _a0, _a1
func (_m *DbRepository) DepositUpdate(_a0 context.Context, _a1 *domain.Deposit) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for DepositUpdate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Deposit) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NotificationCreate provides a mock function with given fields: _a0, _a1
func (_m *DbRepository) NotificationCreate(_a0 context.Context, _a1 *domain.Notification) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for NotificationCreate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Notification) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NotificationGetAllByUserUID provides a mock function with given fields: _a0, _a1
func (_m *DbRepository) NotificationGetAllByUserUID(_a0 context.Context, _a1 string) ([]*domain.Notification, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for NotificationGetAllByUserUID")
	}

	var r0 []*domain.Notification
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*domain.Notification, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*domain.Notification); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Notification)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NotificationGetByUID provides a mock function with given fields: _a0, _a1
func (_m *DbRepository) NotificationGetByUID(_a0 context.Context, _a1 string) (*domain.Notification, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for NotificationGetByUID")
	}

	var r0 *domain.Notification
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Notification, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Notification); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Notification)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NotificationUpdate provides a mock function with given fields: _a0, _a1
func (_m *DbRepository) NotificationUpdate(_a0 context.Context, _a1 *domain.Notification) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for NotificationUpdate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Notification) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PayoutCreate provides a mock function with given fields: _a0, _a1
func (_m *DbRepository) PayoutCreate(_a0 context.Context, _a1 *domain.Payout) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for PayoutCreate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Payout) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PayoutGetAllByUserUID provides a mock function with given fields: _a0, _a1, _a2, _a3
func (_m *DbRepository) PayoutGetAllByUserUID(_a0 context.Context, _a1 string, _a2 int64, _a3 int64) ([]*domain.Payout, error) {
	ret := _m.Called(_a0, _a1, _a2, _a3)

	if len(ret) == 0 {
		panic("no return value specified for PayoutGetAllByUserUID")
	}

	var r0 []*domain.Payout
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int64, int64) ([]*domain.Payout, error)); ok {
		return rf(_a0, _a1, _a2, _a3)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int64, int64) []*domain.Payout); ok {
		r0 = rf(_a0, _a1, _a2, _a3)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Payout)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int64, int64) error); ok {
		r1 = rf(_a0, _a1, _a2, _a3)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ProductGetByCode provides a mock function with given fields: _a0, _a1
func (_m *DbRepository) ProductGetByCode(_a0 context.Context, _a1 string) (*domain.Product, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for ProductGetByCode")
	}

	var r0 *domain.Product
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Product, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Product); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Product)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SafeGetByUID provides a mock function with given fields: _a0, _a1
func (_m *DbRepository) SafeGetByUID(_a0 context.Context, _a1 string) (*domain.Safe, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for SafeGetByUID")
	}

	var r0 *domain.Safe
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Safe, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Safe); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Safe)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SafeUpdate provides a mock function with given fields: _a0, _a1
func (_m *DbRepository) SafeUpdate(_a0 context.Context, _a1 *domain.Safe) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for SafeUpdate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Safe) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TaskDecCount provides a mock function with given fields: _a0, _a1
func (_m *DbRepository) TaskDecCount(_a0 context.Context, _a1 string) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for TaskDecCount")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TaskGetAllWithCompletedByUserUIDAndLocale provides a mock function with given fields: _a0, _a1, _a2
func (_m *DbRepository) TaskGetAllWithCompletedByUserUIDAndLocale(_a0 context.Context, _a1 string, _a2 string) ([]*domain.Task, error) {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for TaskGetAllWithCompletedByUserUIDAndLocale")
	}

	var r0 []*domain.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) ([]*domain.Task, error)); ok {
		return rf(_a0, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) []*domain.Task); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Task)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TaskGetByCode provides a mock function with given fields: _a0, _a1
func (_m *DbRepository) TaskGetByCode(_a0 context.Context, _a1 string) (*domain.Task, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for TaskGetByCode")
	}

	var r0 *domain.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Task, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Task); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Task)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TaskIncCount provides a mock function with given fields: _a0, _a1
func (_m *DbRepository) TaskIncCount(_a0 context.Context, _a1 string) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for TaskIncCount")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TransactionBalanceByUserUIDAndDate provides a mock function with given fields: _a0, _a1, _a2
func (_m *DbRepository) TransactionBalanceByUserUIDAndDate(_a0 context.Context, _a1 string, _a2 time.Time) (int64, error) {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for TransactionBalanceByUserUIDAndDate")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time) (int64, error)); ok {
		return rf(_a0, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time) int64); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, time.Time) error); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TransactionCreate provides a mock function with given fields: _a0, _a1
func (_m *DbRepository) TransactionCreate(_a0 context.Context, _a1 *domain.Transaction) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for TransactionCreate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Transaction) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TransactionDelete provides a mock function with given fields: _a0, _a1
func (_m *DbRepository) TransactionDelete(_a0 context.Context, _a1 *domain.Transaction) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for TransactionDelete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Transaction) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TransactionGetAllByUserUID provides a mock function with given fields: _a0, _a1, _a2, _a3, _a4
func (_m *DbRepository) TransactionGetAllByUserUID(_a0 context.Context, _a1 string, _a2 time.Time, _a3 int64, _a4 int64) ([]*domain.Transaction, error) {
	ret := _m.Called(_a0, _a1, _a2, _a3, _a4)

	if len(ret) == 0 {
		panic("no return value specified for TransactionGetAllByUserUID")
	}

	var r0 []*domain.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time, int64, int64) ([]*domain.Transaction, error)); ok {
		return rf(_a0, _a1, _a2, _a3, _a4)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time, int64, int64) []*domain.Transaction); ok {
		r0 = rf(_a0, _a1, _a2, _a3, _a4)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, time.Time, int64, int64) error); ok {
		r1 = rf(_a0, _a1, _a2, _a3, _a4)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TransactionGetByUserUIDAndTypeAndComboCode provides a mock function with given fields: _a0, _a1, _a2, _a3
func (_m *DbRepository) TransactionGetByUserUIDAndTypeAndComboCode(_a0 context.Context, _a1 string, _a2 domain.TransactionType, _a3 string) (*domain.Transaction, error) {
	ret := _m.Called(_a0, _a1, _a2, _a3)

	if len(ret) == 0 {
		panic("no return value specified for TransactionGetByUserUIDAndTypeAndComboCode")
	}

	var r0 *domain.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, domain.TransactionType, string) (*domain.Transaction, error)); ok {
		return rf(_a0, _a1, _a2, _a3)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, domain.TransactionType, string) *domain.Transaction); ok {
		r0 = rf(_a0, _a1, _a2, _a3)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, domain.TransactionType, string) error); ok {
		r1 = rf(_a0, _a1, _a2, _a3)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TransactionGetByUserUIDAndTypeAndDepositUID provides a mock function with given fields: _a0, _a1, _a2, _a3
func (_m *DbRepository) TransactionGetByUserUIDAndTypeAndDepositUID(_a0 context.Context, _a1 string, _a2 domain.TransactionType, _a3 string) (*domain.Transaction, error) {
	ret := _m.Called(_a0, _a1, _a2, _a3)

	if len(ret) == 0 {
		panic("no return value specified for TransactionGetByUserUIDAndTypeAndDepositUID")
	}

	var r0 *domain.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, domain.TransactionType, string) (*domain.Transaction, error)); ok {
		return rf(_a0, _a1, _a2, _a3)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, domain.TransactionType, string) *domain.Transaction); ok {
		r0 = rf(_a0, _a1, _a2, _a3)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, domain.TransactionType, string) error); ok {
		r1 = rf(_a0, _a1, _a2, _a3)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TransactionGetByUserUIDAndTypeAndTaskCode provides a mock function with given fields: _a0, _a1, _a2, _a3
func (_m *DbRepository) TransactionGetByUserUIDAndTypeAndTaskCode(_a0 context.Context, _a1 string, _a2 domain.TransactionType, _a3 string) (*domain.Transaction, error) {
	ret := _m.Called(_a0, _a1, _a2, _a3)

	if len(ret) == 0 {
		panic("no return value specified for TransactionGetByUserUIDAndTypeAndTaskCode")
	}

	var r0 *domain.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, domain.TransactionType, string) (*domain.Transaction, error)); ok {
		return rf(_a0, _a1, _a2, _a3)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, domain.TransactionType, string) *domain.Transaction); ok {
		r0 = rf(_a0, _a1, _a2, _a3)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, domain.TransactionType, string) error); ok {
		r1 = rf(_a0, _a1, _a2, _a3)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TransactionUpdateAllWithUserUIDAndPayoutUIDAndDate provides a mock function with given fields: _a0, _a1, _a2, _a3
func (_m *DbRepository) TransactionUpdateAllWithUserUIDAndPayoutUIDAndDate(_a0 context.Context, _a1 string, _a2 string, _a3 time.Time) error {
	ret := _m.Called(_a0, _a1, _a2, _a3)

	if len(ret) == 0 {
		panic("no return value specified for TransactionUpdateAllWithUserUIDAndPayoutUIDAndDate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, time.Time) error); ok {
		r0 = rf(_a0, _a1, _a2, _a3)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UserActivityGet provides a mock function with given fields: _a0, _a1
func (_m *DbRepository) UserActivityGet(_a0 context.Context, _a1 string) (*domain.UserActivity, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for UserActivityGet")
	}

	var r0 *domain.UserActivity
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.UserActivity, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.UserActivity); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.UserActivity)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserAuthGetAllUserTg provides a mock function with given fields: _a0, _a1, _a2, _a3, _a4
func (_m *DbRepository) UserAuthGetAllUserTg(_a0 context.Context, _a1 []string, _a2 domain.AuthType, _a3 int64, _a4 int64) ([]*domain.UserTg, error) {
	ret := _m.Called(_a0, _a1, _a2, _a3, _a4)

	if len(ret) == 0 {
		panic("no return value specified for UserAuthGetAllUserTg")
	}

	var r0 []*domain.UserTg
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []string, domain.AuthType, int64, int64) ([]*domain.UserTg, error)); ok {
		return rf(_a0, _a1, _a2, _a3, _a4)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []string, domain.AuthType, int64, int64) []*domain.UserTg); ok {
		r0 = rf(_a0, _a1, _a2, _a3, _a4)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.UserTg)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []string, domain.AuthType, int64, int64) error); ok {
		r1 = rf(_a0, _a1, _a2, _a3, _a4)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserAuthGetByTokenAndType provides a mock function with given fields: _a0, _a1, _a2
func (_m *DbRepository) UserAuthGetByTokenAndType(_a0 context.Context, _a1 string, _a2 domain.AuthType) (*domain.UserAuth, error) {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for UserAuthGetByTokenAndType")
	}

	var r0 *domain.UserAuth
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, domain.AuthType) (*domain.UserAuth, error)); ok {
		return rf(_a0, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, domain.AuthType) *domain.UserAuth); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.UserAuth)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, domain.AuthType) error); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserAuthGetByUserUIDAndType provides a mock function with given fields: _a0, _a1, _a2
func (_m *DbRepository) UserAuthGetByUserUIDAndType(_a0 context.Context, _a1 string, _a2 domain.AuthType) (*domain.UserAuth, error) {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for UserAuthGetByUserUIDAndType")
	}

	var r0 *domain.UserAuth
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, domain.AuthType) (*domain.UserAuth, error)); ok {
		return rf(_a0, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, domain.AuthType) *domain.UserAuth); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.UserAuth)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, domain.AuthType) error); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserBalanceChange provides a mock function with given fields: _a0, _a1, _a2, _a3, _a4
func (_m *DbRepository) UserBalanceChange(_a0 context.Context, _a1 string, _a2 string, _a3 uint8, _a4 int64) error {
	ret := _m.Called(_a0, _a1, _a2, _a3, _a4)

	if len(ret) == 0 {
		panic("no return value specified for UserBalanceChange")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, uint8, int64) error); ok {
		r0 = rf(_a0, _a1, _a2, _a3, _a4)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UserBalanceCreate provides a mock function with given fields: _a0, _a1
func (_m *DbRepository) UserBalanceCreate(_a0 context.Context, _a1 *domain.UserBalance) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for UserBalanceCreate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.UserBalance) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UserBalanceGetByUserUIDAndCurrencyCode provides a mock function with given fields: _a0, _a1, _a2
func (_m *DbRepository) UserBalanceGetByUserUIDAndCurrencyCode(_a0 context.Context, _a1 string, _a2 string) (*domain.UserBalance, error) {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for UserBalanceGetByUserUIDAndCurrencyCode")
	}

	var r0 *domain.UserBalance
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*domain.UserBalance, error)); ok {
		return rf(_a0, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *domain.UserBalance); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.UserBalance)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserBalanceUpdate provides a mock function with given fields: _a0, _a1
func (_m *DbRepository) UserBalanceUpdate(_a0 context.Context, _a1 *domain.UserBalance) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for UserBalanceUpdate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.UserBalance) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UserClaimCreate provides a mock function with given fields: _a0, _a1
func (_m *DbRepository) UserClaimCreate(_a0 context.Context, _a1 *domain.UserClaim) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for UserClaimCreate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.UserClaim) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UserClaimDelete provides a mock function with given fields: _a0, _a1
func (_m *DbRepository) UserClaimDelete(_a0 context.Context, _a1 *domain.UserClaim) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for UserClaimDelete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.UserClaim) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UserClaimGetByUserUIDAndClaimCodeAndTypeAndComboCode provides a mock function with given fields: _a0, _a1, _a2, _a3, _a4
func (_m *DbRepository) UserClaimGetByUserUIDAndClaimCodeAndTypeAndComboCode(_a0 context.Context, _a1 string, _a2 string, _a3 domain.UserClaimType, _a4 string) (*domain.UserClaim, error) {
	ret := _m.Called(_a0, _a1, _a2, _a3, _a4)

	if len(ret) == 0 {
		panic("no return value specified for UserClaimGetByUserUIDAndClaimCodeAndTypeAndComboCode")
	}

	var r0 *domain.UserClaim
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, domain.UserClaimType, string) (*domain.UserClaim, error)); ok {
		return rf(_a0, _a1, _a2, _a3, _a4)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, domain.UserClaimType, string) *domain.UserClaim); ok {
		r0 = rf(_a0, _a1, _a2, _a3, _a4)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.UserClaim)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, domain.UserClaimType, string) error); ok {
		r1 = rf(_a0, _a1, _a2, _a3, _a4)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserClaimGetByUserUIDAndClaimCodeAndTypeAndTaskCode provides a mock function with given fields: _a0, _a1, _a2, _a3, _a4
func (_m *DbRepository) UserClaimGetByUserUIDAndClaimCodeAndTypeAndTaskCode(_a0 context.Context, _a1 string, _a2 string, _a3 domain.UserClaimType, _a4 string) (*domain.UserClaim, error) {
	ret := _m.Called(_a0, _a1, _a2, _a3, _a4)

	if len(ret) == 0 {
		panic("no return value specified for UserClaimGetByUserUIDAndClaimCodeAndTypeAndTaskCode")
	}

	var r0 *domain.UserClaim
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, domain.UserClaimType, string) (*domain.UserClaim, error)); ok {
		return rf(_a0, _a1, _a2, _a3, _a4)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, domain.UserClaimType, string) *domain.UserClaim); ok {
		r0 = rf(_a0, _a1, _a2, _a3, _a4)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.UserClaim)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, domain.UserClaimType, string) error); ok {
		r1 = rf(_a0, _a1, _a2, _a3, _a4)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserClaimGetLastByClaimCodeAndTypeAndUserUID provides a mock function with given fields: _a0, _a1, _a2, _a3
func (_m *DbRepository) UserClaimGetLastByClaimCodeAndTypeAndUserUID(_a0 context.Context, _a1 string, _a2 domain.UserClaimType, _a3 string) (*domain.UserClaim, error) {
	ret := _m.Called(_a0, _a1, _a2, _a3)

	if len(ret) == 0 {
		panic("no return value specified for UserClaimGetLastByClaimCodeAndTypeAndUserUID")
	}

	var r0 *domain.UserClaim
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, domain.UserClaimType, string) (*domain.UserClaim, error)); ok {
		return rf(_a0, _a1, _a2, _a3)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, domain.UserClaimType, string) *domain.UserClaim); ok {
		r0 = rf(_a0, _a1, _a2, _a3)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.UserClaim)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, domain.UserClaimType, string) error); ok {
		r1 = rf(_a0, _a1, _a2, _a3)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserConfigGetByUserUID provides a mock function with given fields: _a0, _a1
func (_m *DbRepository) UserConfigGetByUserUID(_a0 context.Context, _a1 string) (*domain.UserConfig, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for UserConfigGetByUserUID")
	}

	var r0 *domain.UserConfig
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.UserConfig, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.UserConfig); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.UserConfig)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserConfigUpdate provides a mock function with given fields: _a0, _a1
func (_m *DbRepository) UserConfigUpdate(_a0 context.Context, _a1 *domain.UserConfig) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for UserConfigUpdate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.UserConfig) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UserCountByRefUID provides a mock function with given fields: _a0, _a1
func (_m *DbRepository) UserCountByRefUID(_a0 context.Context, _a1 string) (int64, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for UserCountByRefUID")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (int64, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) int64); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserGetByTonWallet provides a mock function with given fields: _a0, _a1
func (_m *DbRepository) UserGetByTonWallet(_a0 context.Context, _a1 string) (*domain.User, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for UserGetByTonWallet")
	}

	var r0 *domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.User, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.User); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserGetByUID provides a mock function with given fields: _a0, _a1
func (_m *DbRepository) UserGetByUID(_a0 context.Context, _a1 string) (*domain.User, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for UserGetByUID")
	}

	var r0 *domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.User, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.User); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserPlaceGetByUserUID provides a mock function with given fields: _a0, _a1
func (_m *DbRepository) UserPlaceGetByUserUID(_a0 context.Context, _a1 string) (*domain.UserPlace, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for UserPlaceGetByUserUID")
	}

	var r0 *domain.UserPlace
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.UserPlace, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.UserPlace); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.UserPlace)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserPlanGetAllByUserUIDAndDate provides a mock function with given fields: _a0, _a1, _a2
func (_m *DbRepository) UserPlanGetAllByUserUIDAndDate(_a0 context.Context, _a1 string, _a2 time.Time) ([]*domain.UserPlan, error) {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for UserPlanGetAllByUserUIDAndDate")
	}

	var r0 []*domain.UserPlan
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time) ([]*domain.UserPlan, error)); ok {
		return rf(_a0, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time) []*domain.UserPlan); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.UserPlan)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, time.Time) error); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserPlanGetByDate provides a mock function with given fields: _a0, _a1, _a2
func (_m *DbRepository) UserPlanGetByDate(_a0 context.Context, _a1 string, _a2 time.Time) (*domain.UserPlan, error) {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for UserPlanGetByDate")
	}

	var r0 *domain.UserPlan
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time) (*domain.UserPlan, error)); ok {
		return rf(_a0, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time) *domain.UserPlan); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.UserPlan)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, time.Time) error); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserProductCreate provides a mock function with given fields: _a0, _a1
func (_m *DbRepository) UserProductCreate(_a0 context.Context, _a1 *domain.UserProduct) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for UserProductCreate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.UserProduct) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UserProductGetAllByUserUIDAndDate provides a mock function with given fields: _a0, _a1, _a2
func (_m *DbRepository) UserProductGetAllByUserUIDAndDate(_a0 context.Context, _a1 string, _a2 time.Time) ([]*domain.UserProduct, error) {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for UserProductGetAllByUserUIDAndDate")
	}

	var r0 []*domain.UserProduct
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time) ([]*domain.UserProduct, error)); ok {
		return rf(_a0, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time) []*domain.UserProduct); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.UserProduct)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, time.Time) error); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserProductGetAllByUserUIDAndProductCategoryAndDate provides a mock function with given fields: _a0, _a1, _a2, _a3
func (_m *DbRepository) UserProductGetAllByUserUIDAndProductCategoryAndDate(_a0 context.Context, _a1 string, _a2 string, _a3 time.Time) ([]*domain.UserProduct, error) {
	ret := _m.Called(_a0, _a1, _a2, _a3)

	if len(ret) == 0 {
		panic("no return value specified for UserProductGetAllByUserUIDAndProductCategoryAndDate")
	}

	var r0 []*domain.UserProduct
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, time.Time) ([]*domain.UserProduct, error)); ok {
		return rf(_a0, _a1, _a2, _a3)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, time.Time) []*domain.UserProduct); ok {
		r0 = rf(_a0, _a1, _a2, _a3)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.UserProduct)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, time.Time) error); ok {
		r1 = rf(_a0, _a1, _a2, _a3)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserProductGetByCategoryAndDate provides a mock function with given fields: _a0, _a1, _a2, _a3
func (_m *DbRepository) UserProductGetByCategoryAndDate(_a0 context.Context, _a1 string, _a2 string, _a3 time.Time) (*domain.UserProduct, error) {
	ret := _m.Called(_a0, _a1, _a2, _a3)

	if len(ret) == 0 {
		panic("no return value specified for UserProductGetByCategoryAndDate")
	}

	var r0 *domain.UserProduct
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, time.Time) (*domain.UserProduct, error)); ok {
		return rf(_a0, _a1, _a2, _a3)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, time.Time) *domain.UserProduct); ok {
		r0 = rf(_a0, _a1, _a2, _a3)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.UserProduct)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, time.Time) error); ok {
		r1 = rf(_a0, _a1, _a2, _a3)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserProductGetByComboUID provides a mock function with given fields: _a0, _a1, _a2
func (_m *DbRepository) UserProductGetByComboUID(_a0 context.Context, _a1 string, _a2 string) (*domain.UserProduct, error) {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for UserProductGetByComboUID")
	}

	var r0 *domain.UserProduct
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*domain.UserProduct, error)); ok {
		return rf(_a0, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *domain.UserProduct); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.UserProduct)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserProductGetLastBoostAndDate provides a mock function with given fields: _a0, _a1, _a2
func (_m *DbRepository) UserProductGetLastBoostAndDate(_a0 context.Context, _a1 string, _a2 time.Time) (*domain.UserProduct, error) {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for UserProductGetLastBoostAndDate")
	}

	var r0 *domain.UserProduct
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time) (*domain.UserProduct, error)); ok {
		return rf(_a0, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time) *domain.UserProduct); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.UserProduct)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, time.Time) error); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserProductGetLastByCategoryAndDate provides a mock function with given fields: _a0, _a1, _a2, _a3
func (_m *DbRepository) UserProductGetLastByCategoryAndDate(_a0 context.Context, _a1 string, _a2 string, _a3 time.Time) (*domain.UserProduct, error) {
	ret := _m.Called(_a0, _a1, _a2, _a3)

	if len(ret) == 0 {
		panic("no return value specified for UserProductGetLastByCategoryAndDate")
	}

	var r0 *domain.UserProduct
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, time.Time) (*domain.UserProduct, error)); ok {
		return rf(_a0, _a1, _a2, _a3)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, time.Time) *domain.UserProduct); ok {
		r0 = rf(_a0, _a1, _a2, _a3)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.UserProduct)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, time.Time) error); ok {
		r1 = rf(_a0, _a1, _a2, _a3)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserRankGetAllByUserUIDAndDate provides a mock function with given fields: _a0, _a1, _a2
func (_m *DbRepository) UserRankGetAllByUserUIDAndDate(_a0 context.Context, _a1 string, _a2 time.Time) ([]*domain.UserRank, error) {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for UserRankGetAllByUserUIDAndDate")
	}

	var r0 []*domain.UserRank
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time) ([]*domain.UserRank, error)); ok {
		return rf(_a0, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time) []*domain.UserRank); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.UserRank)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, time.Time) error); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserRankGetByDate provides a mock function with given fields: _a0, _a1, _a2
func (_m *DbRepository) UserRankGetByDate(_a0 context.Context, _a1 string, _a2 time.Time) (*domain.UserRank, error) {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for UserRankGetByDate")
	}

	var r0 *domain.UserRank
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time) (*domain.UserRank, error)); ok {
		return rf(_a0, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time) *domain.UserRank); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.UserRank)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, time.Time) error); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserSafeGetActiveBySafeUIDsAndUserUID provides a mock function with given fields: _a0, _a1, _a2
func (_m *DbRepository) UserSafeGetActiveBySafeUIDsAndUserUID(_a0 context.Context, _a1 []string, _a2 string) (*domain.UserSafe, error) {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for UserSafeGetActiveBySafeUIDsAndUserUID")
	}

	var r0 *domain.UserSafe
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []string, string) (*domain.UserSafe, error)); ok {
		return rf(_a0, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []string, string) *domain.UserSafe); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.UserSafe)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []string, string) error); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserSafeUpdate provides a mock function with given fields: _a0, _a1
func (_m *DbRepository) UserSafeUpdate(_a0 context.Context, _a1 *domain.UserSafe) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for UserSafeUpdate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.UserSafe) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UserUpdate provides a mock function with given fields: _a0, _a1
func (_m *DbRepository) UserUpdate(_a0 context.Context, _a1 *domain.User) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for UserUpdate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.User) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewDbRepository creates a new instance of DbRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDbRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *DbRepository {
	mock := &DbRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
