version: "3.9"
services:

  api:
    build:
      dockerfile: dev.Dockerfile
      context: .
      target: dev
    volumes:
      - .:/app
    environment:
      - LOG_LEVEL=debug
      - MONGODB_URL=mongodb://user:pass@mongo:27017/aibetrade?authSource=admin&replicaSet=rs0
      - MONGODB_DATABASE=aibetrade
      - TEMPORAL_URL=temporal:7233
      - HTTP_ADDR=0.0.0.0:8081
      - GRAPHQL_ADDRESS=0.0.0.0:8081
      - JWT_SECRET=1234567890
      - API_ROLE=enabled
      - WORKER_ROLE=disabled
      - TG_BOT_API_KEY=7764863883:AAFjxSIwambNkDNs-Cj0UHBFmZbwYpNeRDc
      - CG_BOT_API_KEY=stub
      - TON_NETWORK=testnet
      - TON_WALLET=UQB3-3eO2LtrfhXtEzPgFndxevwD-zhnqGfHZyp5W2_QEB8E
      - PAYMENT_GATEWAY_PAYMENT_SYSTEM_ID=stub
      - PaymentGatewayURL=http://stub
      - PaymentGatewayLogin=stub
      - PaymentGatewayKey=stub
      - NotifierRole=disabled
      - TonListenerRole=
      - TonWorkerRole=
      - ProductRole=
      - AutofarmRole=
    ports:
      - 8081:8081
    depends_on:
      - mongo
      - temporal

  worker:
    build:
      dockerfile: dev.Dockerfile
      context: .
      target: dev
    volumes:
      - .:/app
    environment:
      - LOG_LEVEL=debug
      - MONGODB_URL=mongodb://user:pass@mongo:27017/aibetrade?authSource=admin&replicaSet=rs0
      - MONGODB_DATABASE=aibetrade
      - TEMPORAL_URL=temporal:7233
      - HTTP_ADDR=:8082
      - JWT_SECRET=1234567890
      - API_ROLE=disabled
      - WORKER_ROLE=enabled
      - AUTOFARM_ROLE=disabled
      - PRODUCT_ROLE=disabled
      - NOTIFIER_ROLE=disabled
    ports:
      - 8082:8082
    depends_on:
      - mongo
      - temporal

  mongo:
    image: mongo:6
    container_name: mongo
    restart: always
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27017", "--keyFile", "/etc/mongodb/pki/keyfile"]
    volumes:
      - ./tmp/data/mongo:/data/db
      - /home/ubuntu/mongo-keyfile/rs_keyfile:/etc/mongodb/pki/keyfile:ro
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=pass

  cassandra:
    container_name: cassandra
    image: cassandra
    ports:
      - 9042:9042
    volumes:
      - ./tmp/data/cassandra:/var/lib/cassandra

  temporal:
    container_name: temporal
    depends_on:
      - cassandra
    environment:
      - CASSANDRA_SEEDS=cassandra
    image: temporalio/auto-setup:1.21.6
    ports:
      - 7233:7233
    labels:
      kompose.volume.type: configMap

  temporal-ui:
    container_name: temporal-ui
    depends_on:
      - temporal
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_CORS_ORIGINS=http://127.0.0.1:3000
    image: temporalio/ui
    ports:
      - 8080:8080

  temporal-admin-tools:
    image: temporalio/admin-tools:1.21.6
    depends_on:
      - cassandra
    entrypoint: ["/bin/sh", "-c", "sleep infinity"]

  partner-applications-processor:
    build:
      dockerfile: Dockerfile
      context: .
      args:
        BUILD_TARGET: partner-processor
    environment:
      - LOG_LEVEL=debug
      - MONGODB_URL=mongodb://user:pass@mongo:27017/aibetrade?authSource=admin&replicaSet=rs0
      - MONGODB_DATABASE=aibetrade
    depends_on:
      - mongo
    restart: unless-stopped