package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.47

import (
	"context"
	"fmt"
	"server/internal/domain"
	"server/internal/transport/graphql/generated"
)

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, input generated.AuthLogin) (*generated.AuthRes, error) {
	dAuthReq := &domain.LoginReq{
		Login:    input.Login,
		Password: input.Password,
	}

	authRes, err := r.auth.Login(ctx, dAuthReq)
	if err != nil {
		fmt.Println("LOGIN ERROR:", err)
		return nil, err
	}

	return &generated.AuthRes{
		AuthToken:    authRes.AuthToken,
		RefreshToken: authRes.RefreshToken,
	}, nil
}

// Register is the resolver for the register field.
func (r *mutationResolver) Register(ctx context.Context, input generated.AuthRegister) (*generated.AuthRes, error) {
	locale := "en"
	if input.Locale != nil {
		locale = string(*input.Locale)
	}

	dAuthReq := &domain.RegisterReq{
		Email:      input.Email,
		Nickname:   input.Nickname,
		Password:   input.Password,
		RePassword: input.Repassword,
		RefUid:     input.RefUID,
		Locale:     locale,
	}

	authRes, err := r.auth.Register(ctx, dAuthReq)
	if err != nil {
		fmt.Println("REGISTER ERROR:", err)
		return nil, err
	}

	return &generated.AuthRes{
		AuthToken:    authRes.AuthToken,
		RefreshToken: authRes.RefreshToken,
	}, nil
}

// Refresh is the resolver for the refresh field.
func (r *mutationResolver) Refresh(ctx context.Context, input generated.AuthRefresh) (*generated.AuthRes, error) {
	dAuthRefresh := &domain.RefreshReq{
		RefreshToken: input.RefreshToken,
	}

	authRes, err := r.auth.Refresh(ctx, dAuthRefresh)
	if err != nil {
		return nil, err
	}

	return &generated.AuthRes{
		AuthToken:    authRes.AuthToken,
		RefreshToken: authRes.RefreshToken,
	}, nil
}

// Telegram is the resolver for the telegram field.
func (r *mutationResolver) Telegram(ctx context.Context, input generated.TelegramAuth) (*generated.AuthRes, error) {
	dTelegramAuthReq := &domain.TelegramAuth{
		ID:        input.ID,
		FirstName: input.FirstName,
		LastName:  input.LastName,
		Username:  input.Username,
		PhotoUrl:  input.PhotoURL,
		AuthDate:  input.AuthDate,
		Hash:      input.Hash,
		RefUid:    input.RefUID,
	}

	authRes, err := r.auth.Telegram(ctx, dTelegramAuthReq)
	if err != nil {
		return nil, err
	}

	return &generated.AuthRes{
		AuthToken:    authRes.AuthToken,
		RefreshToken: authRes.RefreshToken,
	}, nil
}

// TelegramApp is the resolver for the telegram_app field.
func (r *mutationResolver) TelegramApp(ctx context.Context, input string) (*generated.AuthRes, error) {
	authRes, err := r.auth.TelegramApp(ctx, input)
	if err != nil {
		return nil, err
	}

	return &generated.AuthRes{
		AuthToken:    authRes.AuthToken,
		RefreshToken: authRes.RefreshToken,
	}, nil
}
