package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.47

import (
	"context"
	"server/internal/domain"
	"server/internal/transport/graphql/generated"
)

// Buy is the resolver for the buy field.
func (r *mutationResolver) Buy(ctx context.Context, input generated.BuyReq) (*generated.BuyRes, error) {
	dUser, err := r.user.Me(ctx)
	if err != nil {
		return nil, err
	}

	buyItem := &domain.BuyReq{
		UserUID:  dUser.UID,
		PlanCode: input.Code,
	}
	buy, err := r.buy.BuyPlan(ctx, buyItem)
	if err != nil {
		return nil, err
	}
	return &generated.BuyRes{
		URL: "",
		UID: buy.PayUID,
	}, nil
}

// BuyProduct is the resolver for the buy_product field.
func (r *mutationResolver) BuyProduct(ctx context.Context, input generated.BuyProductReq) (*generated.BuyRes, error) {
	dUser, err := r.user.Me(ctx)
	if err != nil {
		return nil, err
	}

	buyItem := &domain.BuyProductReq{
		UserUID:     dUser.UID,
		ProductCode: input.Code,
	}
	buy, err := r.buy.BuyProduct(ctx, buyItem)
	if err != nil {
		return nil, err
	}
	return &generated.BuyRes{
		URL: "",
		UID: buy.UID,
	}, nil
}

// Buys is the resolver for the buys field.
func (r *queryResolver) Buys(ctx context.Context, limit int64, skip int64) ([]*generated.Buy, error) {
	dUser, err := r.user.Me(ctx)
	if err != nil {
		return nil, err
	}

	buys, err := r.team.TeamBuyGetAll(ctx, dUser.UID, limit, skip)
	if err != nil {
		return nil, err
	}

	return buyConvertToTransportList(buys), nil
}
