package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.47

import (
	"context"
	"server/internal/transport/graphql/generated"
)

// SetClaim is the resolver for the set_claim field.
func (r *mutationResolver) SetClaim(ctx context.Context, code string) (*generated.ClaimBalance, error) {
	dUser, err := r.user.Me(ctx)
	if err != nil {
		return nil, err
	}

	claimed, err := r.user.UserClaimCreate(ctx, code, dUser.UID)
	if err != nil {
		return nil, err
	}

	bal, err := r.user.ClaimBalance(ctx, code, dUser.UID)
	if err != nil {
		return nil, err
	}

	return &generated.ClaimBalance{
		ClaimCode: claimed.ClaimCode,
		ClaimedAt: claimed.ClaimedAt.UnixMilli(),
		Balance:   bal,
		Precision: int64(claimed.Precision),
	}, nil
}

// GetClaim is the resolver for the get_claim field.
func (r *queryResolver) GetClaim(ctx context.Context, code string) (*generated.Claim, error) {
	dUser, err := r.user.Me(ctx)
	if err != nil {
		return nil, err
	}

	claim, err := r.user.ClaimGet(ctx, code, dUser)
	if err != nil {
		return nil, err
	}

	return claimConvertToTransport(claim), nil
}

// GetClaimBalance is the resolver for the get_claim_balance field.
func (r *queryResolver) GetClaimBalance(ctx context.Context, code string) (*generated.ClaimBalance, error) {
	dUser, err := r.user.Me(ctx)
	if err != nil {
		return nil, err
	}

	claim, err := r.user.ClaimGet(ctx, code, dUser)
	if err != nil {
		return nil, err
	}

	bal, err := r.user.ClaimBalance(ctx, code, dUser.UID)
	if err != nil {
		return nil, err
	}

	lastClaim, err := r.user.UserClaimGetLast(ctx, code, dUser.UID)
	if err != nil {
		return nil, err
	}

	var claimedAt int64
	if lastClaim != nil {
		claimedAt = lastClaim.ClaimedAt.UnixMilli()
	}

	return &generated.ClaimBalance{
		ClaimCode: claim.Code,
		ClaimedAt: claimedAt,
		Balance:   bal,
		Precision: int64(claim.Precision),
	}, nil
}
