package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.47

import (
	"context"
	"server/internal/transport/graphql/generated"
)

// SetCombo is the resolver for the set_combo field.
func (r *mutationResolver) SetCombo(ctx context.Context, code string) (*generated.Combo, error) {
	dUser, err := r.user.Me(ctx)
	if err != nil {
		return nil, err
	}

	combo, err := r.user.Combo(ctx, dUser, code)
	if err != nil {
		return nil, err
	}

	return comboConvertToTransport(combo), nil
}

// Combos is the resolver for the combos field.
func (r *queryResolver) Combos(ctx context.Context) ([]*generated.Combo, error) {
	combos, err := r.user.ComboList(ctx)
	if err != nil {
		return nil, err
	}

	return comboConvertToTransportList(combos), nil
}
