package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.47

import (
	"context"
	"server/internal/transport/graphql/generated"
)

// Cfg is the resolver for the cfg field.
func (r *queryResolver) Cfg(ctx context.Context) (*generated.Cfg, error) {
	cfg, err := r.web.Config(ctx)
	if err != nil {
		return nil, err
	}
	return configConvertToTransport(cfg), nil
}
