package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.47

import (
	"context"
	"server/internal/transport/graphql/generated"
)

// Currencies is the resolver for the currencies field.
func (r *queryResolver) Currencies(ctx context.Context) ([]*generated.Currency, error) {
	currencies, err := r.web.Currencies(ctx)
	if err != nil {
		return nil, err
	}

	res := make([]*generated.Currency, 0, len(currencies))
	for _, c := range currencies {
		res = append(res, &generated.Currency{
			Code:      c.Code,
			Precision: int64(c.Precision),
		})
	}
	return res, nil
}
