package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.47

import (
	"context"
	"fmt"
	"log"
	"server/internal/domain"
	"strconv"
)

// CheckDeposit is the resolver for the check_deposit field.
func (r *mutationResolver) CheckDeposit(ctx context.Context, uid string, lt string) (string, error) {
	dUser, err := r.user.Me(ctx)
	if err != nil {
		return "", err
	}

	if dUser.UID != "SYSTEM" && dUser.UID != "root_ABT_1" {
		return "", domain.NewError(resolverErrorSource).SetCode(domain.ErrAccessDenied)
	}

	ltInt, err := strconv.ParseUint(lt, 10, 64)
	if err != nil {
		return "", err
	}

	err = r.user.CheckDeposit(ctx, uid, ltInt)
	if err != nil {
		return err.Error(), nil
	}
	return fmt.Sprintf("Successfully checked deposit for %s", uid), nil
}

// DepositTotal — GraphQL резолвер для суммы депозитов пользователя
func (r *queryResolver) DepositTotal(ctx context.Context, userUID string) (int64, error) {
	log.Println("[DepositTotal] called for userUid:", userUID)
	total, err := r.user.DepositTotalByUser(ctx, userUID)
	if err != nil {
		log.Println("[DepositTotal] error:", err)
	} else {
		log.Println("[DepositTotal] success, total:", total)
	}
	return total, err
}
