package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.47

import (
	"context"
	"server/internal/transport/graphql/generated"
)

// Dist is the resolver for the dist field.
func (r *mutationResolver) Dist(ctx context.Context) (*generated.DistRes, error) {
	dUser, err := r.user.Me(ctx)
	if err != nil {
		return nil, err
	}

	dDist, err := r.team.DistBuy(ctx, dUser.UID)
	if err != nil {
		return nil, err
	}

	return &generated.DistRes{
		UID: dDist.PayUID,
		URL: "",
	}, nil
}
