package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.47

import (
	"context"
	"server/internal/domain"
	"server/internal/transport/graphql/generated"
	"time"
)

// Notify is the resolver for the notify field.
func (r *mutationResolver) Notify(ctx context.Context, input *generated.Notify) (*generated.Notification, error) {
	dUser, err := r.user.Me(ctx)
	if err != nil {
		return nil, err
	}

	if dUser.UID != "SYSTEM" && dUser.UID != "root_ABT_1" {
		return nil, domain.NewError(resolverErrorSource).SetCode(domain.ErrAccessDenied)
	}

	n := &domain.Notification{
		UID:       domain.GenUID(12),
		Texts:     map[string]string{"ru": input.Texts.Ru, "en": input.Texts.En},
		CreatedAt: time.Now(),
		ToUserUID: input.ToUserUID,
	}

	err = r.user.Notify(ctx, n)
	if err != nil {
		return nil, err
	}

	return notificationConvertToTransport(n), nil
}

// Notifications is the resolver for the notifications field.
func (r *queryResolver) Notifications(ctx context.Context) ([]*generated.Notification, error) {
	dUser, err := r.user.Me(ctx)
	if err != nil {
		return nil, err
	}

	ns, err := r.user.Notifications(ctx, dUser)
	if err != nil {
		return nil, err
	}

	return notificationConvertToTransportList(ns), nil
}
