package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.47

import (
	"context"
	"fmt"
	"server/internal/domain"
	"server/internal/transport/graphql/generated"
)

// CreatePartnerApplication is the resolver for the create_partner_application field.
func (r *mutationResolver) CreatePartnerApplication(ctx context.Context, input generated.PartnerApplicationReq) (*generated.PartnerApplication, error) {
	dUser, err := r.user.Me(ctx)
	if err != nil {
		return nil, err
	}

	req := &domain.PartnerApplicationReq{
		PartnerUID: input.PartnerUID,
		Message:    input.Message,
	}

	application, err := r.team.CreatePartnerApplication(ctx, dUser.UID, req)
	if err != nil {
		return nil, err
	}

	// Convert domain.PartnerApplication to generated.PartnerApplication
	return &generated.PartnerApplication{
		UID:          application.UID,
		ApplicantUID: application.ApplicantUID,
		PartnerUID:   application.PartnerUID,
		Status:       generated.PartnerApplicationStatus(application.Status),
		Message:      application.Message,
		Response:     application.Response,
		CreatedAt:    application.CreatedAt.UnixMilli(),
		ProcessedAt: func() *int64 {
			if application.ProcessedAt == nil {
				return nil
			}
			processedAt := application.ProcessedAt.UnixMilli()
			return &processedAt
		}(),
		ProcessedBy: application.ProcessedBy,
	}, nil
}

// ProcessPartnerApplication is the resolver for the process_partner_application field.
func (r *mutationResolver) ProcessPartnerApplication(ctx context.Context, input generated.PartnerApplicationResponseReq) (*generated.PartnerApplication, error) {
	dUser, err := r.user.Me(ctx)
	if err != nil {
		return nil, err
	}

	req := &domain.PartnerApplicationResponseReq{
		ApplicationUID: input.ApplicationUID,
		Status:         domain.PartnerApplicationStatus(input.Status),
		Response:       input.Response,
	}

	application, err := r.team.ProcessPartnerApplication(ctx, dUser.UID, req)
	if err != nil {
		return nil, err
	}

	// Convert domain.PartnerApplication to generated.PartnerApplication
	return &generated.PartnerApplication{
		UID:          application.UID,
		ApplicantUID: application.ApplicantUID,
		PartnerUID:   application.PartnerUID,
		Status:       generated.PartnerApplicationStatus(application.Status),
		Message:      application.Message,
		Response:     application.Response,
		CreatedAt:    application.CreatedAt.UnixMilli(),
		ProcessedAt: func() *int64 {
			if application.ProcessedAt == nil {
				return nil
			}
			processedAt := application.ProcessedAt.UnixMilli()
			return &processedAt
		}(),
		ProcessedBy: application.ProcessedBy,
	}, nil
}

// PartnerApplications is the resolver for the partner_applications field.
func (r *queryResolver) PartnerApplications(ctx context.Context, limit int64, skip int64) ([]*generated.PartnerApplication, error) {
	dUser, err := r.user.Me(ctx)
	if err != nil {
		return nil, err
	}

	applications, err := r.team.GetPartnerApplications(ctx, dUser.UID, limit, skip)
	if err != nil {
		fmt.Printf("DEBUG: GraphQL resolver error: %v\n", err)
		return nil, err
	}

	fmt.Printf("DEBUG: GraphQL resolver got %d applications\n", len(applications))

	// Convert domain.PartnerApplication to generated.PartnerApplication
	var result []*generated.PartnerApplication
	for _, app := range applications {
		result = append(result, &generated.PartnerApplication{
			UID:          app.UID,
			ApplicantUID: app.ApplicantUID,
			PartnerUID:   app.PartnerUID,
			Status:       generated.PartnerApplicationStatus(app.Status),
			Message:      app.Message,
			Response:     app.Response,
			CreatedAt:    app.CreatedAt.Unix(),
			ProcessedAt: func() *int64 {
				if app.ProcessedAt == nil {
					return nil
				}
				processedAt := app.ProcessedAt.Unix()
				return &processedAt
			}(),
			ProcessedBy: app.ProcessedBy,
		})
	}

	return result, nil
}

// MyApplications is the resolver for the my_applications field.
func (r *queryResolver) MyApplications(ctx context.Context, limit int64, skip int64) ([]*generated.PartnerApplication, error) {
	dUser, err := r.user.Me(ctx)
	if err != nil {
		return nil, err
	}

	applications, err := r.team.GetMyApplications(ctx, dUser.UID, limit, skip)
	if err != nil {
		return nil, err
	}

	// Convert domain.PartnerApplication to generated.PartnerApplication
	var result []*generated.PartnerApplication
	for _, app := range applications {
		result = append(result, &generated.PartnerApplication{
			UID:          app.UID,
			ApplicantUID: app.ApplicantUID,
			PartnerUID:   app.PartnerUID,
			Status:       generated.PartnerApplicationStatus(app.Status),
			Message:      app.Message,
			Response:     app.Response,
			CreatedAt:    app.CreatedAt.Unix(),
			ProcessedAt: func() *int64 {
				if app.ProcessedAt == nil {
					return nil
				}
				processedAt := app.ProcessedAt.Unix()
				return &processedAt
			}(),
			ProcessedBy: app.ProcessedBy,
		})
	}

	return result, nil
}

// PartnerApplicationsCount is the resolver for the partner_applications_count field.
func (r *queryResolver) PartnerApplicationsCount(ctx context.Context) (int64, error) {
	dUser, err := r.user.Me(ctx)
	if err != nil {
		return 0, err
	}

	count, err := r.team.GetPartnerApplicationsCount(ctx, dUser.UID)
	if err != nil {
		return 0, err
	}

	return count, nil
}

// MyApplicationsCount is the resolver for the my_applications_count field.
func (r *queryResolver) MyApplicationsCount(ctx context.Context) (int64, error) {
	dUser, err := r.user.Me(ctx)
	if err != nil {
		return 0, err
	}

	count, err := r.team.GetMyApplicationsCount(ctx, dUser.UID)
	if err != nil {
		return 0, err
	}

	return count, nil
}
