package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.47

import (
	"context"
	"server/internal/transport/graphql/generated"
)

// Plans is the resolver for the plans field.
func (r *queryResolver) Plans(ctx context.Context) ([]*generated.Plan, error) {
	plans, err := r.web.Plans(ctx)
	if err != nil {
		return nil, err
	}

	res := make([]*generated.Plan, 0, len(plans))
	for _, plan := range plans {
		res = append(res, &generated.Plan{
			Code:         plan.Code,
			Period:       int64(plan.Period),
			Price:        plan.Price,
			RetailPrice:  plan.RetailPrice,
			Cv:           plan.Cv,
			CurrencyCode: plan.CurrencyCode,
			RankCode:     plan.RankCode,
			RankPeriod:   int64(plan.RankPeriod),
			Priority:     plan.Priority,
			BotCount:     plan.BotCount,
			MaxDeposit:   plan.MaxDeposit,
		})
	}
	return res, nil
}
