package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.47

import (
	"context"
	"server/internal/domain"
	"server/internal/transport/graphql/generated"
	"strconv"
)

// Prise is the resolver for the prise field.
func (r *mutationResolver) Prise(ctx context.Context, input generated.Prise) ([]*generated.PriseRes, error) {
	dUser, err := r.user.Me(ctx)
	if err != nil {
		return nil, err
	}

	if dUser.UID != "SYSTEM" && dUser.UID != "root_ABT_1" {
		return nil, domain.NewError(resolverErrorSource).SetCode(domain.ErrAccessDenied)
	}

	amount, err := strconv.ParseInt(input.Amount, 10, 64)
	if err != nil {
		return nil, err
	}
	processPrices := &domain.PriseReq{
		ToUserUID: input.ToUserUID,
		Type:      domain.PriseType(input.Type),
		Amount:    amount,
	}
	res, err := r.user.ProcessPrises(ctx, processPrices)
	if err != nil {
		return nil, err
	}

	var results []*generated.PriseRes
	for uid, result := range res {
		results = append(results, &generated.PriseRes{
			UserUID: uid,
			Result:  result,
		})
	}

	return results, nil
}
