package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.47

import (
	"context"
	"server/internal/transport/graphql/generated"
)

// Products is the resolver for the products field.
func (r *queryResolver) Products(ctx context.Context, category *string) ([]*generated.Product, error) {
	var cat string
	if category == nil {
		cat = ""
	} else {
		cat = *category
	}
	products, err := r.web.Products(ctx, cat)
	if err != nil {
		return nil, err
	}

	res := make([]*generated.Product, 0, len(products))
	for _, product := range products {
		var multiplier int64 = 2
		switch product.Code {
		case "premium_month_usd", "premium_year_usd":
			multiplier = 5
		case "premium_month_abt", "premium_year_abt":
			multiplier = 3
		}
		if product.Multiplier > 0 {
			multiplier = product.Multiplier
		}
		res = append(res, &generated.Product{
			Code:         product.Code,
			Category:     product.Category,
			Period:       int64(product.Period),
			Price:        product.Price,
			RetailPrice:  product.RetailPrice,
			Cv:           product.Cv,
			CurrencyCode: product.CurrencyCode,
			Precision:    int64(product.Precision),
			Priority:     product.Priority,
			Multiplier:   multiplier,
			Limit:        product.Limit,
			Count:        product.Count,
		})
	}
	return res, nil
}
