package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.47

import (
	"context"
	"server/internal/transport/graphql/generated"
)

// Ranks is the resolver for the ranks field.
func (r *queryResolver) Ranks(ctx context.Context) ([]*generated.Rank, error) {
	ranks, err := r.web.Ranks(ctx)
	if err != nil {
		return nil, err
	}

	res := make([]*generated.Rank, 0, len(ranks))
	for _, rank := range ranks {
		teamCondition := make([]*generated.RankCondition, 0, len(rank.TeamCondition))
		for _, tc := range rank.TeamCondition {
			teamCondition = append(teamCondition, &generated.RankCondition{
				RankCode: tc.RankCode,
				TeamType: generated.TeamType(tc.TeamType),
				IsRef:    tc.IsRef,
				Count:    int64(tc.Count),
			})
		}
		refBonus := make([]*generated.RankRefBonus, 0, len(rank.TeamCondition))
		for rs, rb := range rank.RefBonus {
			refBonus = append(refBonus, &generated.RankRefBonus{
				PlanCode: rs,
				Percent:  rb,
			})
		}
		var firstBonus *generated.RankGetBonus
		if rank.FirstBonus.Amount > 0 {
			firstBonus = &generated.RankGetBonus{
				Amount: rank.FirstBonus.Amount,
				Months: int64(rank.FirstBonus.Months),
			}
		}
		var approveBonus *generated.RankGetBonus
		if rank.ApproveBonus.Amount > 0 {
			approveBonus = &generated.RankGetBonus{
				Amount: rank.FirstBonus.Amount,
				Months: int64(rank.FirstBonus.Months),
			}
		}
		res = append(res, &generated.Rank{
			Code:          rank.Code,
			MinCv:         rank.MinCv,
			TeamCondition: teamCondition,
			Priority:      rank.Priority,
			BinBonus:      rank.BinBonus,
			BinBonusLimit: rank.BinBonusLimit,
			RefBonus:      refBonus,
			MatchBonus:    rank.MatchBonus,
			FirstBonus:    firstBonus,
			ApproveBonus:  approveBonus,
		})
	}
	return res, nil
}
