package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.47

import (
	"context"
	"server/internal/domain"
	"server/internal/transport/graphql/generated"
)

// HackSafe is the resolver for the hack_safe field.
func (r *mutationResolver) HackSafe(ctx context.Context, code string) (*domain.UserSafe, error) {
	dUser, err := r.user.Me(ctx)
	if err != nil {
		return nil, err
	}

	dSafe, err := r.user.HackSafe(ctx, dUser, code)
	if err != nil {
		return nil, err
	}

	return dSafe, nil
}

// UserSafe is the resolver for the user_safe field.
func (r *queryResolver) UserSafe(ctx context.Context) (*domain.UserSafe, error) {
	dUser, err := r.user.Me(ctx)
	if err != nil {
		return nil, err
	}

	dSafe, err := r.user.GetSafe(ctx, dUser)
	if err != nil {
		return nil, err
	}

	return dSafe, nil
}

// CreatedAt is the resolver for the created_at field.
func (r *userSafeResolver) CreatedAt(ctx context.Context, obj *domain.UserSafe) (int64, error) {
	return obj.CreatedAt.UnixMilli(), nil
}

// ClaimedAt is the resolver for the claimed_at field.
func (r *userSafeResolver) ClaimedAt(ctx context.Context, obj *domain.UserSafe) (int64, error) {
	return obj.ClaimedAt.UnixMilli(), nil
}

// UserSafe returns generated.UserSafeResolver implementation.
func (r *Resolver) UserSafe() generated.UserSafeResolver { return &userSafeResolver{r} }

type userSafeResolver struct{ *Resolver }
