package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.47

import (
	"context"
	"server/internal/domain"
	"server/internal/transport/graphql/generated"
)

// ApproveTask is the resolver for the approve_task field.
func (r *mutationResolver) ApproveTask(ctx context.Context, code string) (*generated.Task, error) {
	dUser, err := r.user.Me(ctx)
	if err != nil {
		return nil, err
	}

	task, err := r.user.TaskApprove(ctx, dUser, code)
	if err != nil {
		return nil, err
	}

	return taskConvertToTransport(task), nil
}

// DeclineTask is the resolver for the decline_task field.
func (r *mutationResolver) DeclineTask(ctx context.Context, code string, tgids []string) ([]*generated.TaskRes, error) {
	dUser, err := r.user.Me(ctx)
	if err != nil {
		return nil, err
	}

	if dUser.UID != "SYSTEM" && dUser.UID != "root_ABT_1" {
		return nil, domain.NewError(resolverErrorSource).SetCode(domain.ErrAccessDenied)
	}

	res, err := r.user.TaskDecline(ctx, code, tgids)
	if err != nil {
		return nil, err
	}

	results := make([]*generated.TaskRes, 0, len(res))
	for uid, rs := range res {
		results = append(results, &generated.TaskRes{
			UserUID: uid,
			Result:  rs,
		})
	}

	return results, nil
}

// Tasks is the resolver for the tasks field.
func (r *queryResolver) Tasks(ctx context.Context) ([]*generated.Task, error) {
	dUser, err := r.user.Me(ctx)
	if err != nil {
		return nil, err
	}

	tasks, err := r.user.TaskGetAllByUser(ctx, dUser)
	if err != nil {
		return nil, err
	}

	return taskConvertToTransportList(tasks), nil
}
