package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.47

import (
	"context"
	"math/big"
	"server/internal/transport/graphql/generated"
)

// AddPartner is the resolver for the add_partner field.
func (r *mutationResolver) AddPartner(ctx context.Context, userUID string, partnerUID string) (bool, error) {
	err := r.team.AddPartner(ctx, userUID, partnerUID)
	if err != nil {
		return false, err
	}
	return true, nil
}

// RemovePartner is the resolver for the remove_partner field.
func (r *mutationResolver) RemovePartner(ctx context.Context, userUID string, partnerUID string) (bool, error) {
	err := r.team.RemovePartner(ctx, userUID, partnerUID)
	if err != nil {
		return false, err
	}
	return true, nil
}

// TeamRef is the resolver for the team_ref field.
func (r *queryResolver) TeamRef(ctx context.Context, userUID *string) ([]*generated.TeamUser, error) {
	dUser, err := r.user.Me(ctx)
	if err != nil {
		return nil, err
	}

	userUid := dUser.UID
	if userUID != nil {
		userUid = *userUID
	}

	dTeamUsers, err := r.team.TeamUserGetAllRef(ctx, userUid)
	if err != nil {
		return nil, err
	}

	return teamUserConvertToTransportList(dTeamUsers), nil
}

// TeamBin is the resolver for the team_bin field.
func (r *queryResolver) TeamBin(ctx context.Context, userUID *string, rows int64) ([]*generated.TeamUser, error) {
	dUser, err := r.user.Me(ctx)
	if err != nil {
		return nil, err
	}

	userUid := dUser.UID
	if userUID != nil {
		userUid = *userUID
	}

	dTeamUsers, err := r.team.TeamUserGetAllBin(ctx, userUid, big.NewInt(rows))
	if err != nil {
		return nil, err
	}

	return teamUserConvertToTransportList(dTeamUsers), nil
}

// TeamMatch is the resolver for the team_match field.
func (r *queryResolver) TeamMatch(ctx context.Context, userUID *string) ([]*generated.TeamUser, error) {
	dUser, err := r.user.Me(ctx)
	if err != nil {
		return nil, err
	}

	userUid := dUser.UID
	if userUID != nil {
		userUid = *userUID
	}

	dTeamUsers, err := r.team.TeamUserGetAllMatch(ctx, userUid)
	if err != nil {
		return nil, err
	}

	return teamUserConvertToTransportList(dTeamUsers), nil
}

// FriendsCount is the resolver for the friends_count field.
func (r *queryResolver) FriendsCount(ctx context.Context, userUID string) (int64, error) {
	return r.team.FriendsGetCountByUserUID(ctx, userUID)
}

// Friends is the resolver for the friends field.
func (r *queryResolver) Friends(ctx context.Context, userUID string, limit int64, skip int64) ([]*generated.FriendUser, error) {
	users, err := r.team.FriendsGetAllByUserUID(ctx, userUID, limit, skip)
	if err != nil {
		return nil, err
	}

	return friendUserConvertToTransportList(users), nil
}

// PartnersCount is the resolver for the partners_count field.
func (r *queryResolver) PartnersCount(ctx context.Context, userUID string) (int64, error) {
	return r.team.PartnersGetCountByUserUID(ctx, userUID)
}
