package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.47

import (
	"context"
	"server/internal/domain"
	"server/internal/transport/graphql/generated"
	"time"

	"github.com/99designs/gqlgen/graphql"
)

// SetTeamType is the resolver for the set_team_type field.
func (r *mutationResolver) SetTeamType(ctx context.Context, typeArg generated.TeamType) (*generated.UserConfig, error) {
	dUser, err := r.user.Me(ctx)
	if err != nil {
		return nil, err
	}

	conf, err := r.user.SetTeamType(ctx, dUser, domain.UserTeamType(typeArg))
	if err != nil {
		return nil, err
	}

	return userConfigConvertToTransport(conf), nil
}

// SetRef is the resolver for the set_ref field.
func (r *mutationResolver) SetRef(ctx context.Context, uid string) (string, error) {
	dUser, err := r.user.Me(ctx)
	if err != nil {
		return "", err
	}

	dUser, err = r.user.SetRef(ctx, dUser, uid)
	if err != nil {
		return "", err
	}

	return uid, nil
}

// Payout is the resolver for the payout field.
func (r *mutationResolver) Payout(ctx context.Context, input generated.PayoutReq) (*generated.Payout, error) {
	dUser, err := r.user.Me(ctx)
	if err != nil {
		return nil, err
	}

	payout := &domain.Payout{
		UID:           domain.GenUID(12),
		UserUID:       dUser.UID,
		CurrencyCode:  input.CurrencyCode,
		MethodCode:    input.MethodCode,
		AccountNumber: input.AccountNumber,
		AccountName:   input.AccountName,
		CreatedAt:     time.Now().UTC(),
	}

	err = r.user.Payout(ctx, dUser, payout)
	if err != nil {
		return nil, err
	}

	return payoutConvertToTransport(payout), nil
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*generated.User, error) {
	dUser, err := r.user.Me(ctx)
	if err != nil {
		return nil, err
	}

	fieldsArray := graphql.CollectAllFields(ctx)
	fields := map[string]bool{}
	for _, field := range fieldsArray {
		fields[field] = true
	}

	var leftAmount int64
	if _, ok := fields["left"]; ok {
		leftAmount, err = r.user.AmountByUserAndSide(ctx, dUser, domain.UserTeamTypeLeft)
		if err != nil {
			leftAmount = 0
		}
	}

	var rightAmount int64
	if _, ok := fields["right"]; ok {
		rightAmount, err = r.user.AmountByUserAndSide(ctx, dUser, domain.UserTeamTypeRight)
		if err != nil {
			rightAmount = 0
		}
	}

	var ranks []*generated.UserRank
	if _, ok := fields["ranks"]; ok {
		dRanks, err := r.user.Ranks(ctx, dUser)
		if err == nil {
			ranks = userRankConvertToTransportList(dRanks)
		}
	}

	var plans []*generated.UserPlan
	if _, ok := fields["plans"]; ok {
		dPlans, err := r.user.Plans(ctx, dUser)
		if err == nil {
			plans = userPlanConvertToTransportList(dPlans)
		}
	}

	var products []*generated.UserProduct
	if _, ok := fields["products"]; ok {
		dProducts, err := r.user.Products(ctx, dUser)
		if err == nil {
			products = userProductConvertToTransportList(dProducts)
		}
	}

	var rank *generated.UserRank
	if _, ok := fields["rank"]; ok {
		dRank, err := r.user.Rank(ctx, dUser)
		if err == nil {
			rank = userRankConvertToTransport(dRank)
		}
	}

	var plan *generated.UserPlan
	if _, ok := fields["plan"]; ok {
		dPlan, err := r.user.Plan(ctx, dUser)
		if err == nil {
			plan = userPlanConvertToTransport(dPlan)
		}
	}

	var place *generated.UserPlace
	role := generated.UserRoleClient
	dPlace, err := r.user.Place(ctx, dUser)
	if err == nil && dPlace != nil {
		place = userPlaceConvertToTransport(dPlace)
		role = generated.UserRoleDistributor
	}

	var activity *generated.UserActivity
	if _, ok := fields["activity"]; ok {
		dUserActivity, err := r.user.Activity(ctx, dUser)
		if err == nil {
			activity = userActivityConvertToTransport(dUserActivity)
		}
	}

	conf := &generated.UserConfig{}
	if _, ok := fields["config"]; ok {
		dConf, _ := r.user.Config(ctx, dUser)
		if dConf == nil {
			dConf = &domain.UserConfig{}
		}
		conf = userConfigConvertToTransport(dConf)
	}

	var balance int64 = 0
	if _, ok := fields["balance"]; ok {
		balance, _ = r.user.Balance(ctx, dUser)
	}

	var level *generated.UserLevel
	if _, ok := fields["level"]; ok {
		dLevel, _ := r.auth.UserLevel(ctx, dUser)
		level = userLevelConvertToTransport(dLevel)
	}

	var teamCount int64
	if _, ok := fields["team_count"]; ok {
		teamCount, _ = r.user.TeamCount(ctx, dUser)
	}

	var isPremium bool
	var premiumInvites int
	var premiumUntil time.Time
	multiplier := 1
	_, okPrem := fields["is_premium"]
	_, okPremUntil := fields["premium_until"]
	_, okPremiumInvites := fields["premium_invites"]
	if okPrem || okPremUntil || okPremiumInvites {
		premiumUntil, premiumInvites, multiplier, _ = r.user.IsPremium(ctx, dUser)
		if !premiumUntil.IsZero() {
			isPremium = true
		}
	}

	var isAutofarm bool
	var autofarmUntil time.Time
	_, okAutofarm := fields["is_autofarm"]
	_, okAutofarmUntil := fields["autofarm_until"]
	if okAutofarm || okAutofarmUntil {
		autofarmUntil, _ = r.user.IsAutofarm(ctx, dUser)
		if !autofarmUntil.IsZero() {
			isAutofarm = true
		}
	}

	var activeBoost *generated.UserProduct
	if _, ok := fields["active_boost"]; ok {
		dBoost, _ := r.user.GetUserLastBoost(ctx, dUser.UID)
		activeBoost = userProductConvertToTransport(dBoost)
	}

	return &generated.User{
		UID:               dUser.UID,
		RefUID:            dUser.RefUID,
		LimRefUID:         dUser.LimRefUID,
		Email:             dUser.Email,
		Nickname:          dUser.Nickname,
		PhotoURL:          dUser.PhotoUrl,
		CreatedAt:         dUser.CreatedAt.UnixMilli(),
		Left:              leftAmount,
		Right:             rightAmount,
		Ranks:             ranks,
		Rank:              rank,
		Plans:             plans,
		Plan:              plan,
		Place:             place,
		Role:              role,
		Activity:          activity,
		Config:            conf,
		Balance:           balance,
		Level:             level,
		TgID:              dUser.TgID,
		TgUsername:        dUser.TgUsername,
		TeamCount:         teamCount,
		TonWallet:         dUser.TonWallet,
		UnlimInvite:       dUser.UnlimInvite,
		Products:          products,
		IsPremium:         isPremium,
		PremiumUntil:      premiumUntil.UnixMilli(),
		PremiumInvites:    int64(premiumInvites),
		PremiumMultiplier: int64(multiplier),
		IsAutofarm:        isAutofarm,
		AutofarmUntil:     autofarmUntil.UnixMilli(),
		ActiveBoost:       activeBoost,
	}, nil
}

// Payouts is the resolver for the payouts field.
func (r *queryResolver) Payouts(ctx context.Context, limit int64, skip int64) ([]*generated.Payout, error) {
	dUser, err := r.user.Me(ctx)
	if err != nil {
		return nil, err
	}

	payouts, err := r.user.Payouts(ctx, dUser, limit, skip)
	if err != nil {
		return nil, err
	}

	return payoutConvertToTransportList(payouts), nil
}

// Levels is the resolver for the levels field.
func (r *queryResolver) Levels(ctx context.Context) ([]*generated.UserLevel, error) {
	levels, err := r.auth.Levels(ctx)
	if err != nil {
		return nil, err
	}

	return userLevelConvertToTransportList(levels), nil
}
