// Code generated by mockery v2.38.0. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "server/internal/domain"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// DbRepository is an autogenerated mock type for the DbRepository type
type DbRepository struct {
	mock.Mock
}

// ClaimGetByCode provides a mock function with given fields: _a0, _a1
func (_m *DbRepository) ClaimGetByCode(_a0 context.Context, _a1 string) (*domain.Claim, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for ClaimGetByCode")
	}

	var r0 *domain.Claim
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Claim, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Claim); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Claim)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ConfigGet provides a mock function with given fields: _a0
func (_m *DbRepository) ConfigGet(_a0 context.Context) (*domain.Config, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for ConfigGet")
	}

	var r0 *domain.Config
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*domain.Config, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *domain.Config); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Config)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserAuthCreate provides a mock function with given fields: _a0, _a1
func (_m *DbRepository) UserAuthCreate(_a0 context.Context, _a1 *domain.UserAuth) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for UserAuthCreate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.UserAuth) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UserAuthGetByTokenAndType provides a mock function with given fields: _a0, _a1, _a2
func (_m *DbRepository) UserAuthGetByTokenAndType(_a0 context.Context, _a1 string, _a2 domain.AuthType) (*domain.UserAuth, error) {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for UserAuthGetByTokenAndType")
	}

	var r0 *domain.UserAuth
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, domain.AuthType) (*domain.UserAuth, error)); ok {
		return rf(_a0, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, domain.AuthType) *domain.UserAuth); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.UserAuth)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, domain.AuthType) error); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserAuthGetByUserUIDAndType provides a mock function with given fields: _a0, _a1, _a2
func (_m *DbRepository) UserAuthGetByUserUIDAndType(_a0 context.Context, _a1 string, _a2 domain.AuthType) (*domain.UserAuth, error) {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for UserAuthGetByUserUIDAndType")
	}

	var r0 *domain.UserAuth
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, domain.AuthType) (*domain.UserAuth, error)); ok {
		return rf(_a0, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, domain.AuthType) *domain.UserAuth); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.UserAuth)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, domain.AuthType) error); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserBalanceCreate provides a mock function with given fields: _a0, _a1
func (_m *DbRepository) UserBalanceCreate(_a0 context.Context, _a1 *domain.UserBalance) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for UserBalanceCreate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.UserBalance) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UserBalanceGetByUserUIDAndCurrencyCode provides a mock function with given fields: _a0, _a1, _a2
func (_m *DbRepository) UserBalanceGetByUserUIDAndCurrencyCode(_a0 context.Context, _a1 string, _a2 string) (*domain.UserBalance, error) {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for UserBalanceGetByUserUIDAndCurrencyCode")
	}

	var r0 *domain.UserBalance
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*domain.UserBalance, error)); ok {
		return rf(_a0, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *domain.UserBalance); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.UserBalance)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserBalanceUpdate provides a mock function with given fields: _a0, _a1
func (_m *DbRepository) UserBalanceUpdate(_a0 context.Context, _a1 *domain.UserBalance) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for UserBalanceUpdate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.UserBalance) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UserClaimCreate provides a mock function with given fields: _a0, _a1
func (_m *DbRepository) UserClaimCreate(_a0 context.Context, _a1 *domain.UserClaim) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for UserClaimCreate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.UserClaim) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UserCountByRefUID provides a mock function with given fields: _a0, _a1
func (_m *DbRepository) UserCountByRefUID(_a0 context.Context, _a1 string) (int64, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for UserCountByRefUID")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (int64, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) int64); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserCreate provides a mock function with given fields: _a0, _a1
func (_m *DbRepository) UserCreate(_a0 context.Context, _a1 *domain.User) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for UserCreate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.User) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UserGetByEmail provides a mock function with given fields: _a0, _a1
func (_m *DbRepository) UserGetByEmail(_a0 context.Context, _a1 string) (*domain.User, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for UserGetByEmail")
	}

	var r0 *domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.User, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.User); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserGetByNickname provides a mock function with given fields: _a0, _a1
func (_m *DbRepository) UserGetByNickname(_a0 context.Context, _a1 string) (*domain.User, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for UserGetByNickname")
	}

	var r0 *domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.User, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.User); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserGetByUID provides a mock function with given fields: _a0, _a1
func (_m *DbRepository) UserGetByUID(_a0 context.Context, _a1 string) (*domain.User, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for UserGetByUID")
	}

	var r0 *domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.User, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.User); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserPlaceGetByUserUID provides a mock function with given fields: _a0, _a1
func (_m *DbRepository) UserPlaceGetByUserUID(_a0 context.Context, _a1 string) (*domain.UserPlace, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for UserPlaceGetByUserUID")
	}

	var r0 *domain.UserPlace
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.UserPlace, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.UserPlace); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.UserPlace)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserProductGetByCategoryAndDate provides a mock function with given fields: _a0, _a1, _a2, _a3
func (_m *DbRepository) UserProductGetByCategoryAndDate(_a0 context.Context, _a1 string, _a2 string, _a3 time.Time) (*domain.UserProduct, error) {
	ret := _m.Called(_a0, _a1, _a2, _a3)

	if len(ret) == 0 {
		panic("no return value specified for UserProductGetByCategoryAndDate")
	}

	var r0 *domain.UserProduct
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, time.Time) (*domain.UserProduct, error)); ok {
		return rf(_a0, _a1, _a2, _a3)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, time.Time) *domain.UserProduct); ok {
		r0 = rf(_a0, _a1, _a2, _a3)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.UserProduct)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, time.Time) error); ok {
		r1 = rf(_a0, _a1, _a2, _a3)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserProductGetLastBoostAndDate provides a mock function with given fields: _a0, _a1, _a2
func (_m *DbRepository) UserProductGetLastBoostAndDate(_a0 context.Context, _a1 string, _a2 time.Time) (*domain.UserProduct, error) {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for UserProductGetLastBoostAndDate")
	}

	var r0 *domain.UserProduct
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time) (*domain.UserProduct, error)); ok {
		return rf(_a0, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time) *domain.UserProduct); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.UserProduct)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, time.Time) error); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserSafeCreate provides a mock function with given fields: _a0, _a1
func (_m *DbRepository) UserSafeCreate(_a0 context.Context, _a1 *domain.UserSafe) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for UserSafeCreate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.UserSafe) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UserSafeGetActiveBySafeUIDsAndUserUID provides a mock function with given fields: _a0, _a1, _a2
func (_m *DbRepository) UserSafeGetActiveBySafeUIDsAndUserUID(_a0 context.Context, _a1 []string, _a2 string) (*domain.UserSafe, error) {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for UserSafeGetActiveBySafeUIDsAndUserUID")
	}

	var r0 *domain.UserSafe
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []string, string) (*domain.UserSafe, error)); ok {
		return rf(_a0, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []string, string) *domain.UserSafe); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.UserSafe)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []string, string) error); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserSafeUpdateSecret provides a mock function with given fields: _a0, _a1, _a2
func (_m *DbRepository) UserSafeUpdateSecret(_a0 context.Context, _a1 string, _a2 string) error {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for UserSafeUpdateSecret")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewDbRepository creates a new instance of DbRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDbRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *DbRepository {
	mock := &DbRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
