// Code generated by mockery v2.38.0. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "server/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// DbRepository is an autogenerated mock type for the DbRepository type
type DbRepository struct {
	mock.Mock
}

// ConfigGet provides a mock function with given fields: _a0
func (_m *DbRepository) ConfigGet(_a0 context.Context) (*domain.Config, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for ConfigGet")
	}

	var r0 *domain.Config
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*domain.Config, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *domain.Config); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Config)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CurrencyGetAll provides a mock function with given fields: _a0
func (_m *DbRepository) CurrencyGetAll(_a0 context.Context) ([]*domain.Currency, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for CurrencyGetAll")
	}

	var r0 []*domain.Currency
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*domain.Currency, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*domain.Currency); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Currency)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PlanGetAll provides a mock function with given fields: _a0
func (_m *DbRepository) PlanGetAll(_a0 context.Context) ([]*domain.Plan, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for PlanGetAll")
	}

	var r0 []*domain.Plan
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*domain.Plan, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*domain.Plan); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Plan)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ProductGetAllIsActive provides a mock function with given fields: _a0
func (_m *DbRepository) ProductGetAllIsActive(_a0 context.Context) ([]*domain.Product, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for ProductGetAllIsActive")
	}

	var r0 []*domain.Product
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*domain.Product, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*domain.Product); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Product)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ProductGetAllIsActiveByCategory provides a mock function with given fields: _a0, _a1
func (_m *DbRepository) ProductGetAllIsActiveByCategory(_a0 context.Context, _a1 string) ([]*domain.Product, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for ProductGetAllIsActiveByCategory")
	}

	var r0 []*domain.Product
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*domain.Product, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*domain.Product); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Product)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RankGetAll provides a mock function with given fields: _a0
func (_m *DbRepository) RankGetAll(_a0 context.Context) ([]*domain.Rank, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for RankGetAll")
	}

	var r0 []*domain.Rank
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*domain.Rank, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*domain.Rank); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Rank)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserGetByUID provides a mock function with given fields: _a0, _a1
func (_m *DbRepository) UserGetByUID(_a0 context.Context, _a1 string) (*domain.User, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for UserGetByUID")
	}

	var r0 *domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.User, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.User); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewDbRepository creates a new instance of DbRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDbRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *DbRepository {
	mock := &DbRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
