// Code generated by mockery v2.38.0. DO NOT EDIT.

package mocks

import (
	context "context"
	big "math/big"

	domain "server/internal/domain"

	mock "github.com/stretchr/testify/mock"

	options "go.mongodb.org/mongo-driver/mongo/options"

	time "time"
)

// DbRepository is an autogenerated mock type for the DbRepository type
type DbRepository struct {
	mock.Mock
}

// BuyGetAllWith provides a mock function with given fields: _a0, _a1, _a2
func (_m *DbRepository) BuyGetAllWith(_a0 context.Context, _a1 interface{}, _a2 *options.FindOptions) ([]*domain.Buy, error) {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for BuyGetAllWith")
	}

	var r0 []*domain.Buy
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, interface{}, *options.FindOptions) ([]*domain.Buy, error)); ok {
		return rf(_a0, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func(context.Context, interface{}, *options.FindOptions) []*domain.Buy); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Buy)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, interface{}, *options.FindOptions) error); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// BuySumAllByField provides a mock function with given fields: _a0, _a1, _a2
func (_m *DbRepository) BuySumAllByField(_a0 context.Context, _a1 interface{}, _a2 string) (int64, error) {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for BuySumAllByField")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, interface{}, string) (int64, error)); ok {
		return rf(_a0, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func(context.Context, interface{}, string) int64); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, interface{}, string) error); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// BuyUpdate provides a mock function with given fields: _a0, _a1
func (_m *DbRepository) BuyUpdate(_a0 context.Context, _a1 *domain.Buy) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for BuyUpdate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Buy) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ClaimGetByCode provides a mock function with given fields: _a0, _a1
func (_m *DbRepository) ClaimGetByCode(_a0 context.Context, _a1 string) (*domain.Claim, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for ClaimGetByCode")
	}

	var r0 *domain.Claim
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Claim, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Claim); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Claim)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ConfigGet provides a mock function with given fields: _a0
func (_m *DbRepository) ConfigGet(_a0 context.Context) (*domain.Config, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for ConfigGet")
	}

	var r0 *domain.Config
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*domain.Config, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *domain.Config); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Config)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DistCreate provides a mock function with given fields: _a0, _a1
func (_m *DbRepository) DistCreate(_a0 context.Context, _a1 *domain.Dist) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for DistCreate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Dist) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DistGetByPayUID provides a mock function with given fields: _a0, _a1
func (_m *DbRepository) DistGetByPayUID(_a0 context.Context, _a1 string) (*domain.Dist, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for DistGetByPayUID")
	}

	var r0 *domain.Dist
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Dist, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Dist); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Dist)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DistGetByUID provides a mock function with given fields: _a0, _a1
func (_m *DbRepository) DistGetByUID(_a0 context.Context, _a1 string) (*domain.Dist, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for DistGetByUID")
	}

	var r0 *domain.Dist
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Dist, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Dist); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Dist)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DistUpdate provides a mock function with given fields: _a0, _a1
func (_m *DbRepository) DistUpdate(_a0 context.Context, _a1 *domain.Dist) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for DistUpdate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Dist) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PlanGetByCode provides a mock function with given fields: _a0, _a1
func (_m *DbRepository) PlanGetByCode(_a0 context.Context, _a1 string) (*domain.Plan, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for PlanGetByCode")
	}

	var r0 *domain.Plan
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Plan, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Plan); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Plan)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RankGetByCode provides a mock function with given fields: _a0, _a1
func (_m *DbRepository) RankGetByCode(_a0 context.Context, _a1 string) (*domain.Rank, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for RankGetByCode")
	}

	var r0 *domain.Rank
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Rank, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Rank); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Rank)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RankGetByMinCv provides a mock function with given fields: _a0, _a1
func (_m *DbRepository) RankGetByMinCv(_a0 context.Context, _a1 int64) (*domain.Rank, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for RankGetByMinCv")
	}

	var r0 *domain.Rank
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*domain.Rank, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *domain.Rank); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Rank)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RankGetNext provides a mock function with given fields: _a0, _a1
func (_m *DbRepository) RankGetNext(_a0 context.Context, _a1 *domain.Rank) (*domain.Rank, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for RankGetNext")
	}

	var r0 *domain.Rank
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Rank) (*domain.Rank, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Rank) *domain.Rank); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Rank)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.Rank) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TransactionCreate provides a mock function with given fields: _a0, _a1
func (_m *DbRepository) TransactionCreate(_a0 context.Context, _a1 *domain.Transaction) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for TransactionCreate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Transaction) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TransactionDeleteAllByBuyUIDAndType provides a mock function with given fields: _a0, _a1, _a2
func (_m *DbRepository) TransactionDeleteAllByBuyUIDAndType(_a0 context.Context, _a1 string, _a2 domain.TransactionType) error {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for TransactionDeleteAllByBuyUIDAndType")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, domain.TransactionType) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TransactionDeleteAllByUserUIDAndBuyUIDAndType provides a mock function with given fields: _a0, _a1, _a2, _a3
func (_m *DbRepository) TransactionDeleteAllByUserUIDAndBuyUIDAndType(_a0 context.Context, _a1 string, _a2 string, _a3 domain.TransactionType) error {
	ret := _m.Called(_a0, _a1, _a2, _a3)

	if len(ret) == 0 {
		panic("no return value specified for TransactionDeleteAllByUserUIDAndBuyUIDAndType")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, domain.TransactionType) error); ok {
		r0 = rf(_a0, _a1, _a2, _a3)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// TransactionGetByUserUIDAndType provides a mock function with given fields: _a0, _a1, _a2
func (_m *DbRepository) TransactionGetByUserUIDAndType(_a0 context.Context, _a1 string, _a2 domain.TransactionType) (*domain.Transaction, error) {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for TransactionGetByUserUIDAndType")
	}

	var r0 *domain.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, domain.TransactionType) (*domain.Transaction, error)); ok {
		return rf(_a0, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, domain.TransactionType) *domain.Transaction); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, domain.TransactionType) error); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TransactionGetByUserUIDAndTypeAndRankCode provides a mock function with given fields: _a0, _a1, _a2, _a3
func (_m *DbRepository) TransactionGetByUserUIDAndTypeAndRankCode(_a0 context.Context, _a1 string, _a2 domain.TransactionType, _a3 string) (*domain.Transaction, error) {
	ret := _m.Called(_a0, _a1, _a2, _a3)

	if len(ret) == 0 {
		panic("no return value specified for TransactionGetByUserUIDAndTypeAndRankCode")
	}

	var r0 *domain.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, domain.TransactionType, string) (*domain.Transaction, error)); ok {
		return rf(_a0, _a1, _a2, _a3)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, domain.TransactionType, string) *domain.Transaction); ok {
		r0 = rf(_a0, _a1, _a2, _a3)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, domain.TransactionType, string) error); ok {
		r1 = rf(_a0, _a1, _a2, _a3)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TransactionSumByUserUIDAndTypeAndDates provides a mock function with given fields: _a0, _a1, _a2, _a3, _a4
func (_m *DbRepository) TransactionSumByUserUIDAndTypeAndDates(_a0 context.Context, _a1 string, _a2 domain.TransactionType, _a3 time.Time, _a4 time.Time) (int64, error) {
	ret := _m.Called(_a0, _a1, _a2, _a3, _a4)

	if len(ret) == 0 {
		panic("no return value specified for TransactionSumByUserUIDAndTypeAndDates")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, domain.TransactionType, time.Time, time.Time) (int64, error)); ok {
		return rf(_a0, _a1, _a2, _a3, _a4)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, domain.TransactionType, time.Time, time.Time) int64); ok {
		r0 = rf(_a0, _a1, _a2, _a3, _a4)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, domain.TransactionType, time.Time, time.Time) error); ok {
		r1 = rf(_a0, _a1, _a2, _a3, _a4)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserActivityCreate provides a mock function with given fields: _a0, _a1
func (_m *DbRepository) UserActivityCreate(_a0 context.Context, _a1 *domain.UserActivity) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for UserActivityCreate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.UserActivity) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UserActivityGet provides a mock function with given fields: _a0, _a1
func (_m *DbRepository) UserActivityGet(_a0 context.Context, _a1 string) (*domain.UserActivity, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for UserActivityGet")
	}

	var r0 *domain.UserActivity
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.UserActivity, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.UserActivity); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.UserActivity)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserActivityGetByDate provides a mock function with given fields: _a0, _a1, _a2
func (_m *DbRepository) UserActivityGetByDate(_a0 context.Context, _a1 string, _a2 time.Time) (*domain.UserActivity, error) {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for UserActivityGetByDate")
	}

	var r0 *domain.UserActivity
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time) (*domain.UserActivity, error)); ok {
		return rf(_a0, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time) *domain.UserActivity); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.UserActivity)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, time.Time) error); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserActivityUpdate provides a mock function with given fields: _a0, _a1
func (_m *DbRepository) UserActivityUpdate(_a0 context.Context, _a1 *domain.UserActivity) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for UserActivityUpdate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.UserActivity) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UserAggregateWith provides a mock function with given fields: _a0, _a1, _a2, _a3
func (_m *DbRepository) UserAggregateWith(_a0 context.Context, _a1 interface{}, _a2 []string, _a3 time.Time) ([]*domain.TeamUser, error) {
	ret := _m.Called(_a0, _a1, _a2, _a3)

	if len(ret) == 0 {
		panic("no return value specified for UserAggregateWith")
	}

	var r0 []*domain.TeamUser
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, interface{}, []string, time.Time) ([]*domain.TeamUser, error)); ok {
		return rf(_a0, _a1, _a2, _a3)
	}
	if rf, ok := ret.Get(0).(func(context.Context, interface{}, []string, time.Time) []*domain.TeamUser); ok {
		r0 = rf(_a0, _a1, _a2, _a3)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.TeamUser)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, interface{}, []string, time.Time) error); ok {
		r1 = rf(_a0, _a1, _a2, _a3)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserBalanceCreate provides a mock function with given fields: _a0, _a1
func (_m *DbRepository) UserBalanceCreate(_a0 context.Context, _a1 *domain.UserBalance) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for UserBalanceCreate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.UserBalance) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UserBalanceGetByUserUIDAndCurrencyCode provides a mock function with given fields: _a0, _a1, _a2
func (_m *DbRepository) UserBalanceGetByUserUIDAndCurrencyCode(_a0 context.Context, _a1 string, _a2 string) (*domain.UserBalance, error) {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for UserBalanceGetByUserUIDAndCurrencyCode")
	}

	var r0 *domain.UserBalance
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*domain.UserBalance, error)); ok {
		return rf(_a0, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *domain.UserBalance); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.UserBalance)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserBalanceUpdate provides a mock function with given fields: _a0, _a1
func (_m *DbRepository) UserBalanceUpdate(_a0 context.Context, _a1 *domain.UserBalance) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for UserBalanceUpdate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.UserBalance) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UserClaimCreate provides a mock function with given fields: _a0, _a1
func (_m *DbRepository) UserClaimCreate(_a0 context.Context, _a1 *domain.UserClaim) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for UserClaimCreate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.UserClaim) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UserClaimGetLastByClaimCodeAndTypeAndUserUID provides a mock function with given fields: _a0, _a1, _a2, _a3
func (_m *DbRepository) UserClaimGetLastByClaimCodeAndTypeAndUserUID(_a0 context.Context, _a1 string, _a2 domain.UserClaimType, _a3 string) (*domain.UserClaim, error) {
	ret := _m.Called(_a0, _a1, _a2, _a3)

	if len(ret) == 0 {
		panic("no return value specified for UserClaimGetLastByClaimCodeAndTypeAndUserUID")
	}

	var r0 *domain.UserClaim
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, domain.UserClaimType, string) (*domain.UserClaim, error)); ok {
		return rf(_a0, _a1, _a2, _a3)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, domain.UserClaimType, string) *domain.UserClaim); ok {
		r0 = rf(_a0, _a1, _a2, _a3)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.UserClaim)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, domain.UserClaimType, string) error); ok {
		r1 = rf(_a0, _a1, _a2, _a3)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserConfigCreate provides a mock function with given fields: _a0, _a1
func (_m *DbRepository) UserConfigCreate(_a0 context.Context, _a1 *domain.UserConfig) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for UserConfigCreate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.UserConfig) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UserConfigGetByUserUID provides a mock function with given fields: _a0, _a1
func (_m *DbRepository) UserConfigGetByUserUID(_a0 context.Context, _a1 string) (*domain.UserConfig, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for UserConfigGetByUserUID")
	}

	var r0 *domain.UserConfig
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.UserConfig, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.UserConfig); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.UserConfig)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserConfigUpdate provides a mock function with given fields: _a0, _a1
func (_m *DbRepository) UserConfigUpdate(_a0 context.Context, _a1 *domain.UserConfig) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for UserConfigUpdate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.UserConfig) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UserCountByRefUID provides a mock function with given fields: _a0, _a1
func (_m *DbRepository) UserCountByRefUID(_a0 context.Context, _a1 string) (int64, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for UserCountByRefUID")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (int64, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) int64); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserGetAllWithCountByRefUID provides a mock function with given fields: _a0, _a1, _a2, _a3
func (_m *DbRepository) UserGetAllWithCountByRefUID(_a0 context.Context, _a1 string, _a2 int64, _a3 int64) ([]*domain.User, error) {
	ret := _m.Called(_a0, _a1, _a2, _a3)

	if len(ret) == 0 {
		panic("no return value specified for UserGetAllWithCountByRefUID")
	}

	var r0 []*domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int64, int64) ([]*domain.User, error)); ok {
		return rf(_a0, _a1, _a2, _a3)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int64, int64) []*domain.User); ok {
		r0 = rf(_a0, _a1, _a2, _a3)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int64, int64) error); ok {
		r1 = rf(_a0, _a1, _a2, _a3)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserGetByUID provides a mock function with given fields: _a0, _a1
func (_m *DbRepository) UserGetByUID(_a0 context.Context, _a1 string) (*domain.User, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for UserGetByUID")
	}

	var r0 *domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.User, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.User); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserPlaceAggregateWith provides a mock function with given fields: _a0, _a1, _a2, _a3
func (_m *DbRepository) UserPlaceAggregateWith(_a0 context.Context, _a1 interface{}, _a2 []string, _a3 time.Time) ([]*domain.TeamUser, error) {
	ret := _m.Called(_a0, _a1, _a2, _a3)

	if len(ret) == 0 {
		panic("no return value specified for UserPlaceAggregateWith")
	}

	var r0 []*domain.TeamUser
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, interface{}, []string, time.Time) ([]*domain.TeamUser, error)); ok {
		return rf(_a0, _a1, _a2, _a3)
	}
	if rf, ok := ret.Get(0).(func(context.Context, interface{}, []string, time.Time) []*domain.TeamUser); ok {
		r0 = rf(_a0, _a1, _a2, _a3)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.TeamUser)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, interface{}, []string, time.Time) error); ok {
		r1 = rf(_a0, _a1, _a2, _a3)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserPlaceCreate provides a mock function with given fields: _a0, _a1
func (_m *DbRepository) UserPlaceCreate(_a0 context.Context, _a1 *domain.UserPlace) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for UserPlaceCreate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.UserPlace) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UserPlaceGet provides a mock function with given fields: _a0, _a1, _a2
func (_m *DbRepository) UserPlaceGet(_a0 context.Context, _a1 interface{}, _a2 *options.FindOneOptions) (*domain.UserPlace, error) {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for UserPlaceGet")
	}

	var r0 *domain.UserPlace
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, interface{}, *options.FindOneOptions) (*domain.UserPlace, error)); ok {
		return rf(_a0, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func(context.Context, interface{}, *options.FindOneOptions) *domain.UserPlace); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.UserPlace)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, interface{}, *options.FindOneOptions) error); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserPlaceGetAll provides a mock function with given fields: _a0, _a1, _a2
func (_m *DbRepository) UserPlaceGetAll(_a0 context.Context, _a1 interface{}, _a2 *options.FindOptions) ([]*domain.UserPlace, error) {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for UserPlaceGetAll")
	}

	var r0 []*domain.UserPlace
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, interface{}, *options.FindOptions) ([]*domain.UserPlace, error)); ok {
		return rf(_a0, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func(context.Context, interface{}, *options.FindOptions) []*domain.UserPlace); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.UserPlace)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, interface{}, *options.FindOptions) error); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserPlaceGetByMatchUID provides a mock function with given fields: _a0, _a1
func (_m *DbRepository) UserPlaceGetByMatchUID(_a0 context.Context, _a1 string) (*domain.UserPlace, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for UserPlaceGetByMatchUID")
	}

	var r0 *domain.UserPlace
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.UserPlace, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.UserPlace); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.UserPlace)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserPlaceGetByRowCol provides a mock function with given fields: _a0, _a1, _a2
func (_m *DbRepository) UserPlaceGetByRowCol(_a0 context.Context, _a1 *big.Int, _a2 *big.Int) (*domain.UserPlace, error) {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for UserPlaceGetByRowCol")
	}

	var r0 *domain.UserPlace
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *big.Int, *big.Int) (*domain.UserPlace, error)); ok {
		return rf(_a0, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *big.Int, *big.Int) *domain.UserPlace); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.UserPlace)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *big.Int, *big.Int) error); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserPlaceGetByUserUID provides a mock function with given fields: _a0, _a1
func (_m *DbRepository) UserPlaceGetByUserUID(_a0 context.Context, _a1 string) (*domain.UserPlace, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for UserPlaceGetByUserUID")
	}

	var r0 *domain.UserPlace
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.UserPlace, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.UserPlace); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.UserPlace)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserPlanGetByDate provides a mock function with given fields: _a0, _a1, _a2
func (_m *DbRepository) UserPlanGetByDate(_a0 context.Context, _a1 string, _a2 time.Time) (*domain.UserPlan, error) {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for UserPlanGetByDate")
	}

	var r0 *domain.UserPlan
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time) (*domain.UserPlan, error)); ok {
		return rf(_a0, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time) *domain.UserPlan); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.UserPlan)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, time.Time) error); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserRankCountAllByRankCode provides a mock function with given fields: _a0, _a1
func (_m *DbRepository) UserRankCountAllByRankCode(_a0 context.Context, _a1 interface{}) (map[string]uint64, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for UserRankCountAllByRankCode")
	}

	var r0 map[string]uint64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, interface{}) (map[string]uint64, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, interface{}) map[string]uint64); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]uint64)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, interface{}) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserRankCreate provides a mock function with given fields: _a0, _a1
func (_m *DbRepository) UserRankCreate(_a0 context.Context, _a1 *domain.UserRank) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for UserRankCreate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.UserRank) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UserRankGetAllWith provides a mock function with given fields: _a0, _a1, _a2
func (_m *DbRepository) UserRankGetAllWith(_a0 context.Context, _a1 interface{}, _a2 *options.FindOptions) ([]*domain.UserRank, error) {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for UserRankGetAllWith")
	}

	var r0 []*domain.UserRank
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, interface{}, *options.FindOptions) ([]*domain.UserRank, error)); ok {
		return rf(_a0, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func(context.Context, interface{}, *options.FindOptions) []*domain.UserRank); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.UserRank)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, interface{}, *options.FindOptions) error); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserRankGetByDate provides a mock function with given fields: _a0, _a1, _a2
func (_m *DbRepository) UserRankGetByDate(_a0 context.Context, _a1 string, _a2 time.Time) (*domain.UserRank, error) {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for UserRankGetByDate")
	}

	var r0 *domain.UserRank
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time) (*domain.UserRank, error)); ok {
		return rf(_a0, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time) *domain.UserRank); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.UserRank)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, time.Time) error); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserRankGetByDateAndType provides a mock function with given fields: _a0, _a1, _a2, _a3
func (_m *DbRepository) UserRankGetByDateAndType(_a0 context.Context, _a1 string, _a2 time.Time, _a3 domain.UserRankType) (*domain.UserRank, error) {
	ret := _m.Called(_a0, _a1, _a2, _a3)

	if len(ret) == 0 {
		panic("no return value specified for UserRankGetByDateAndType")
	}

	var r0 *domain.UserRank
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time, domain.UserRankType) (*domain.UserRank, error)); ok {
		return rf(_a0, _a1, _a2, _a3)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time, domain.UserRankType) *domain.UserRank); ok {
		r0 = rf(_a0, _a1, _a2, _a3)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.UserRank)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, time.Time, domain.UserRankType) error); ok {
		r1 = rf(_a0, _a1, _a2, _a3)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserRankGetByUserUID provides a mock function with given fields: _a0, _a1
func (_m *DbRepository) UserRankGetByUserUID(_a0 context.Context, _a1 string) (*domain.UserRank, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for UserRankGetByUserUID")
	}

	var r0 *domain.UserRank
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.UserRank, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.UserRank); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.UserRank)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserRankUpdate provides a mock function with given fields: _a0, _a1
func (_m *DbRepository) UserRankUpdate(_a0 context.Context, _a1 *domain.UserRank) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for UserRankUpdate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.UserRank) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewDbRepository creates a new instance of DbRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDbRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *DbRepository {
	mock := &DbRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
