// Code generated by mockery v2.38.0. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "server/internal/domain"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// PBClient is an autogenerated mock type for the PBClient type
type PBClient struct {
	mock.Mock
}

// OrderCancel provides a mock function with given fields: ctx, id
func (_m *PBClient) OrderCancel(ctx context.Context, id uuid.UUID) (bool, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for OrderCancel")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (bool, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) bool); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OrderCreate provides a mock function with given fields: ctx, order
func (_m *PBClient) OrderCreate(ctx context.Context, order domain.OrderCreateReq) (*domain.CreateOrderResp, error) {
	ret := _m.Called(ctx, order)

	if len(ret) == 0 {
		panic("no return value specified for OrderCreate")
	}

	var r0 *domain.CreateOrderResp
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.OrderCreateReq) (*domain.CreateOrderResp, error)); ok {
		return rf(ctx, order)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.OrderCreateReq) *domain.CreateOrderResp); ok {
		r0 = rf(ctx, order)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.CreateOrderResp)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.OrderCreateReq) error); ok {
		r1 = rf(ctx, order)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OrderInfo provides a mock function with given fields: ctx, id
func (_m *PBClient) OrderInfo(ctx context.Context, id uuid.UUID) (*domain.OrderInfo, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for OrderInfo")
	}

	var r0 *domain.OrderInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.OrderInfo, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.OrderInfo); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.OrderInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewPBClient creates a new instance of PBClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPBClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *PBClient {
	mock := &PBClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
