// Code generated by mockery v2.38.0. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "server/internal/domain"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// BuyService is an autogenerated mock type for the BuyService type
type BuyService struct {
	mock.Mock
}

// Approved provides a mock function with given fields: _a0, _a1, _a2
func (_m *BuyService) Approved(_a0 context.Context, _a1 *domain.Buy, _a2 time.Time) (*domain.Buy, error) {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for Approved")
	}

	var r0 *domain.Buy
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Buy, time.Time) (*domain.Buy, error)); ok {
		return rf(_a0, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Buy, time.Time) *domain.Buy); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Buy)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.Buy, time.Time) error); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// BuyPay provides a mock function with given fields: _a0, _a1
func (_m *BuyService) BuyPay(_a0 context.Context, _a1 *domain.Buy) (*domain.Buy, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for BuyPay")
	}

	var r0 *domain.Buy
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Buy) (*domain.Buy, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Buy) *domain.Buy); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Buy)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.Buy) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// BuySetRowCol provides a mock function with given fields: _a0, _a1, _a2
func (_m *BuyService) BuySetRowCol(_a0 context.Context, _a1 *domain.Buy, _a2 *domain.UserPlace) (*domain.Buy, error) {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for BuySetRowCol")
	}

	var r0 *domain.Buy
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Buy, *domain.UserPlace) (*domain.Buy, error)); ok {
		return rf(_a0, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Buy, *domain.UserPlace) *domain.Buy); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Buy)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.Buy, *domain.UserPlace) error); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Cancelled provides a mock function with given fields: _a0, _a1, _a2
func (_m *BuyService) Cancelled(_a0 context.Context, _a1 *domain.Buy, _a2 time.Time) (*domain.Buy, error) {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for Cancelled")
	}

	var r0 *domain.Buy
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Buy, time.Time) (*domain.Buy, error)); ok {
		return rf(_a0, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Buy, time.Time) *domain.Buy); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Buy)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.Buy, time.Time) error); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Charged provides a mock function with given fields: _a0, _a1, _a2
func (_m *BuyService) Charged(_a0 context.Context, _a1 *domain.Buy, _a2 time.Time) (*domain.Buy, error) {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for Charged")
	}

	var r0 *domain.Buy
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Buy, time.Time) (*domain.Buy, error)); ok {
		return rf(_a0, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Buy, time.Time) *domain.Buy); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Buy)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.Buy, time.Time) error); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetRefUsersUp provides a mock function with given fields: _a0, _a1, _a2
func (_m *BuyService) GetRefUsersUp(_a0 context.Context, _a1 string, _a2 int) ([]*domain.User, error) {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for GetRefUsersUp")
	}

	var r0 []*domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int) ([]*domain.User, error)); ok {
		return rf(_a0, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int) []*domain.User); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int) error); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Init provides a mock function with given fields: _a0, _a1
func (_m *BuyService) Init(_a0 context.Context, _a1 *domain.Buy) (*domain.Buy, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Init")
	}

	var r0 *domain.Buy
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Buy) (*domain.Buy, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Buy) *domain.Buy); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Buy)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.Buy) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InitAutofarm provides a mock function with given fields: _a0, _a1
func (_m *BuyService) InitAutofarm(_a0 context.Context, _a1 *domain.UserProduct) (*domain.UserProduct, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for InitAutofarm")
	}

	var r0 *domain.UserProduct
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.UserProduct) (*domain.UserProduct, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.UserProduct) *domain.UserProduct); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.UserProduct)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.UserProduct) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InitPaid provides a mock function with given fields: _a0, _a1
func (_m *BuyService) InitPaid(_a0 context.Context, _a1 *domain.Buy) (*domain.Buy, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for InitPaid")
	}

	var r0 *domain.Buy
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Buy) (*domain.Buy, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Buy) *domain.Buy); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Buy)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.Buy) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Paid provides a mock function with given fields: _a0, _a1, _a2
func (_m *BuyService) Paid(_a0 context.Context, _a1 *domain.Buy, _a2 time.Time) (*domain.Buy, error) {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for Paid")
	}

	var r0 *domain.Buy
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Buy, time.Time) (*domain.Buy, error)); ok {
		return rf(_a0, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Buy, time.Time) *domain.Buy); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Buy)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.Buy, time.Time) error); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Plan provides a mock function with given fields: _a0, _a1
func (_m *BuyService) Plan(_a0 context.Context, _a1 *domain.Buy) (*domain.Plan, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Plan")
	}

	var r0 *domain.Plan
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Buy) (*domain.Plan, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Buy) *domain.Plan); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Plan)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.Buy) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PlanAdd provides a mock function with given fields: _a0, _a1, _a2
func (_m *BuyService) PlanAdd(_a0 context.Context, _a1 *domain.Buy, _a2 *domain.Plan) (*domain.UserPlan, error) {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for PlanAdd")
	}

	var r0 *domain.UserPlan
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Buy, *domain.Plan) (*domain.UserPlan, error)); ok {
		return rf(_a0, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Buy, *domain.Plan) *domain.UserPlan); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.UserPlan)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.Buy, *domain.Plan) error); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PlanEnd provides a mock function with given fields: _a0, _a1, _a2
func (_m *BuyService) PlanEnd(_a0 context.Context, _a1 *domain.Buy, _a2 *domain.UserPlan) (*domain.UserPlan, error) {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for PlanEnd")
	}

	var r0 *domain.UserPlan
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Buy, *domain.UserPlan) (*domain.UserPlan, error)); ok {
		return rf(_a0, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Buy, *domain.UserPlan) *domain.UserPlan); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.UserPlan)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.Buy, *domain.UserPlan) error); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Product provides a mock function with given fields: _a0, _a1
func (_m *BuyService) Product(_a0 context.Context, _a1 *domain.Buy) (*domain.Product, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Product")
	}

	var r0 *domain.Product
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Buy) (*domain.Product, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Buy) *domain.Product); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Product)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.Buy) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ProductAdd provides a mock function with given fields: _a0, _a1, _a2
func (_m *BuyService) ProductAdd(_a0 context.Context, _a1 *domain.Buy, _a2 *domain.Product) (*domain.UserProduct, error) {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for ProductAdd")
	}

	var r0 *domain.UserProduct
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Buy, *domain.Product) (*domain.UserProduct, error)); ok {
		return rf(_a0, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Buy, *domain.Product) *domain.UserProduct); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.UserProduct)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.Buy, *domain.Product) error); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ProductApply provides a mock function with given fields: _a0, _a1
func (_m *BuyService) ProductApply(_a0 context.Context, _a1 *domain.UserProduct) (*domain.UserProduct, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for ProductApply")
	}

	var r0 *domain.UserProduct
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.UserProduct) (*domain.UserProduct, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.UserProduct) *domain.UserProduct); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.UserProduct)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.UserProduct) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RankAddFromPlan provides a mock function with given fields: _a0, _a1, _a2
func (_m *BuyService) RankAddFromPlan(_a0 context.Context, _a1 *domain.Buy, _a2 *domain.Plan) (*domain.UserRank, error) {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for RankAddFromPlan")
	}

	var r0 *domain.UserRank
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Buy, *domain.Plan) (*domain.UserRank, error)); ok {
		return rf(_a0, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Buy, *domain.Plan) *domain.UserRank); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.UserRank)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.Buy, *domain.Plan) error); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RankEnd provides a mock function with given fields: _a0, _a1, _a2
func (_m *BuyService) RankEnd(_a0 context.Context, _a1 *domain.Buy, _a2 *domain.UserRank) (*domain.UserRank, error) {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for RankEnd")
	}

	var r0 *domain.UserRank
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Buy, *domain.UserRank) (*domain.UserRank, error)); ok {
		return rf(_a0, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Buy, *domain.UserRank) *domain.UserRank); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.UserRank)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.Buy, *domain.UserRank) error); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RefUserCharge provides a mock function with given fields: _a0, _a1, _a2, _a3
func (_m *BuyService) RefUserCharge(_a0 context.Context, _a1 *domain.Buy, _a2 *domain.User, _a3 int) (int64, error) {
	ret := _m.Called(_a0, _a1, _a2, _a3)

	if len(ret) == 0 {
		panic("no return value specified for RefUserCharge")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Buy, *domain.User, int) (int64, error)); ok {
		return rf(_a0, _a1, _a2, _a3)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Buy, *domain.User, int) int64); ok {
		r0 = rf(_a0, _a1, _a2, _a3)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.Buy, *domain.User, int) error); ok {
		r1 = rf(_a0, _a1, _a2, _a3)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Refund provides a mock function with given fields: _a0, _a1, _a2
func (_m *BuyService) Refund(_a0 context.Context, _a1 *domain.Buy, _a2 time.Time) (*domain.Buy, error) {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for Refund")
	}

	var r0 *domain.Buy
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Buy, time.Time) (*domain.Buy, error)); ok {
		return rf(_a0, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Buy, time.Time) *domain.Buy); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Buy)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.Buy, time.Time) error); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewBuyService creates a new instance of BuyService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBuyService(t interface {
	mock.TestingT
	Cleanup(func())
}) *BuyService {
	mock := &BuyService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
