// Code generated by mockery v2.38.0. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "server/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// TeamService is an autogenerated mock type for the TeamService type
type TeamService struct {
	mock.Mock
}

// BuyClientSetRowCol provides a mock function with given fields: _a0, _a1, _a2
func (_m *TeamService) BuyClientSetRowCol(_a0 context.Context, _a1 *domain.Buy, _a2 *domain.UserPlace) (*domain.Buy, error) {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for BuyClientSetRowCol")
	}

	var r0 *domain.Buy
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Buy, *domain.UserPlace) (*domain.Buy, error)); ok {
		return rf(_a0, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Buy, *domain.UserPlace) *domain.Buy); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Buy)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.Buy, *domain.UserPlace) error); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CalculateActivity provides a mock function with given fields: _a0, _a1, _a2
func (_m *TeamService) CalculateActivity(_a0 context.Context, _a1 *domain.Buy, _a2 *domain.UserPlace) (*domain.UserActivity, error) {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for CalculateActivity")
	}

	var r0 *domain.UserActivity
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Buy, *domain.UserPlace) (*domain.UserActivity, error)); ok {
		return rf(_a0, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Buy, *domain.UserPlace) *domain.UserActivity); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.UserActivity)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.Buy, *domain.UserPlace) error); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CalculateNextRank provides a mock function with given fields: _a0, _a1, _a2
func (_m *TeamService) CalculateNextRank(_a0 context.Context, _a1 *domain.Buy, _a2 *domain.UserPlace) (*domain.UserRank, error) {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for CalculateNextRank")
	}

	var r0 *domain.UserRank
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Buy, *domain.UserPlace) (*domain.UserRank, error)); ok {
		return rf(_a0, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Buy, *domain.UserPlace) *domain.UserRank); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.UserRank)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.Buy, *domain.UserPlace) error); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ChargeApproveRankBonus provides a mock function with given fields: _a0, _a1, _a2
func (_m *TeamService) ChargeApproveRankBonus(_a0 context.Context, _a1 *domain.Buy, _a2 *domain.UserPlace) (*domain.Buy, error) {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for ChargeApproveRankBonus")
	}

	var r0 *domain.Buy
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Buy, *domain.UserPlace) (*domain.Buy, error)); ok {
		return rf(_a0, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Buy, *domain.UserPlace) *domain.Buy); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Buy)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.Buy, *domain.UserPlace) error); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ChargeBinBonus provides a mock function with given fields: _a0, _a1, _a2, _a3
func (_m *TeamService) ChargeBinBonus(_a0 context.Context, _a1 *domain.Buy, _a2 *domain.UserPlace, _a3 int) (*domain.Transaction, error) {
	ret := _m.Called(_a0, _a1, _a2, _a3)

	if len(ret) == 0 {
		panic("no return value specified for ChargeBinBonus")
	}

	var r0 *domain.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Buy, *domain.UserPlace, int) (*domain.Transaction, error)); ok {
		return rf(_a0, _a1, _a2, _a3)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Buy, *domain.UserPlace, int) *domain.Transaction); ok {
		r0 = rf(_a0, _a1, _a2, _a3)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.Buy, *domain.UserPlace, int) error); ok {
		r1 = rf(_a0, _a1, _a2, _a3)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ChargeCoinRefBonus provides a mock function with given fields: _a0, _a1
func (_m *TeamService) ChargeCoinRefBonus(_a0 context.Context, _a1 *domain.Buy) (*domain.Buy, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for ChargeCoinRefBonus")
	}

	var r0 *domain.Buy
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Buy) (*domain.Buy, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Buy) *domain.Buy); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Buy)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.Buy) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ChargeFastStartBonus provides a mock function with given fields: _a0, _a1, _a2
func (_m *TeamService) ChargeFastStartBonus(_a0 context.Context, _a1 *domain.Buy, _a2 *domain.UserPlace) (*domain.Buy, error) {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for ChargeFastStartBonus")
	}

	var r0 *domain.Buy
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Buy, *domain.UserPlace) (*domain.Buy, error)); ok {
		return rf(_a0, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Buy, *domain.UserPlace) *domain.Buy); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Buy)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.Buy, *domain.UserPlace) error); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ChargeFirstRankBonus provides a mock function with given fields: _a0, _a1, _a2
func (_m *TeamService) ChargeFirstRankBonus(_a0 context.Context, _a1 *domain.Buy, _a2 *domain.UserPlace) (*domain.Buy, error) {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for ChargeFirstRankBonus")
	}

	var r0 *domain.Buy
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Buy, *domain.UserPlace) (*domain.Buy, error)); ok {
		return rf(_a0, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Buy, *domain.UserPlace) *domain.Buy); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Buy)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.Buy, *domain.UserPlace) error); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ChargeMatchBonus provides a mock function with given fields: _a0, _a1, _a2, _a3, _a4
func (_m *TeamService) ChargeMatchBonus(_a0 context.Context, _a1 *domain.Buy, _a2 *domain.UserPlace, _a3 *domain.Transaction, _a4 int) (*domain.Transaction, error) {
	ret := _m.Called(_a0, _a1, _a2, _a3, _a4)

	if len(ret) == 0 {
		panic("no return value specified for ChargeMatchBonus")
	}

	var r0 *domain.Transaction
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Buy, *domain.UserPlace, *domain.Transaction, int) (*domain.Transaction, error)); ok {
		return rf(_a0, _a1, _a2, _a3, _a4)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Buy, *domain.UserPlace, *domain.Transaction, int) *domain.Transaction); ok {
		r0 = rf(_a0, _a1, _a2, _a3, _a4)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Transaction)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.Buy, *domain.UserPlace, *domain.Transaction, int) error); ok {
		r1 = rf(_a0, _a1, _a2, _a3, _a4)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ChargeRefBonus provides a mock function with given fields: _a0, _a1
func (_m *TeamService) ChargeRefBonus(_a0 context.Context, _a1 *domain.Buy) (*domain.Buy, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for ChargeRefBonus")
	}

	var r0 *domain.Buy
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Buy) (*domain.Buy, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Buy) *domain.Buy); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Buy)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.Buy) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PlaceCreateForRef provides a mock function with given fields: _a0, _a1
func (_m *TeamService) PlaceCreateForRef(_a0 context.Context, _a1 string) (*domain.UserPlace, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for PlaceCreateForRef")
	}

	var r0 *domain.UserPlace
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.UserPlace, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.UserPlace); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.UserPlace)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PlaceGetAllUp provides a mock function with given fields: _a0, _a1
func (_m *TeamService) PlaceGetAllUp(_a0 context.Context, _a1 *domain.UserPlace) ([]*domain.UserPlace, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for PlaceGetAllUp")
	}

	var r0 []*domain.UserPlace
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.UserPlace) ([]*domain.UserPlace, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.UserPlace) []*domain.UserPlace); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.UserPlace)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.UserPlace) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PlaceGetRefUpByBuy provides a mock function with given fields: _a0, _a1
func (_m *TeamService) PlaceGetRefUpByBuy(_a0 context.Context, _a1 *domain.Buy) (*domain.UserPlace, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for PlaceGetRefUpByBuy")
	}

	var r0 *domain.UserPlace
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Buy) (*domain.UserPlace, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Buy) *domain.UserPlace); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.UserPlace)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.Buy) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PlaceRefGetAllUp provides a mock function with given fields: _a0, _a1, _a2
func (_m *TeamService) PlaceRefGetAllUp(_a0 context.Context, _a1 *domain.Buy, _a2 *domain.UserPlace) ([]*domain.UserPlace, error) {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for PlaceRefGetAllUp")
	}

	var r0 []*domain.UserPlace
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Buy, *domain.UserPlace) ([]*domain.UserPlace, error)); ok {
		return rf(_a0, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Buy, *domain.UserPlace) []*domain.UserPlace); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.UserPlace)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.Buy, *domain.UserPlace) error); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserPlaceGet provides a mock function with given fields: _a0, _a1
func (_m *TeamService) UserPlaceGet(_a0 context.Context, _a1 *domain.Buy) (*domain.UserPlace, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for UserPlaceGet")
	}

	var r0 *domain.UserPlace
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Buy) (*domain.UserPlace, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Buy) *domain.UserPlace); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.UserPlace)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.Buy) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserRankSetRowCol provides a mock function with given fields: _a0, _a1, _a2
func (_m *TeamService) UserRankSetRowCol(_a0 context.Context, _a1 *domain.UserRank, _a2 *domain.UserPlace) (*domain.UserRank, error) {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for UserRankSetRowCol")
	}

	var r0 *domain.UserRank
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.UserRank, *domain.UserPlace) (*domain.UserRank, error)); ok {
		return rf(_a0, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *domain.UserRank, *domain.UserPlace) *domain.UserRank); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.UserRank)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *domain.UserRank, *domain.UserPlace) error); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewTeamService creates a new instance of TeamService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTeamService(t interface {
	mock.TestingT
	Cleanup(func())
}) *TeamService {
	mock := &TeamService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
