// Code generated by mockery v2.38.0. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "server/internal/domain"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// DbRepository is an autogenerated mock type for the DbRepository type
type DbRepository struct {
	mock.Mock
}

// BuyCreate provides a mock function with given fields: _a0, _a1
func (_m *DbRepository) BuyCreate(_a0 context.Context, _a1 *domain.Buy) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for BuyCreate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Buy) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// BuyGetByPayUID provides a mock function with given fields: _a0, _a1
func (_m *DbRepository) BuyGetByPayUID(_a0 context.Context, _a1 string) (*domain.Buy, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for BuyGetByPayUID")
	}

	var r0 *domain.Buy
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Buy, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Buy); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Buy)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// BuyGetByUID provides a mock function with given fields: _a0, _a1
func (_m *DbRepository) BuyGetByUID(_a0 context.Context, _a1 string) (*domain.Buy, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for BuyGetByUID")
	}

	var r0 *domain.Buy
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Buy, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Buy); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Buy)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// BuyUpdate provides a mock function with given fields: _a0, _a1
func (_m *DbRepository) BuyUpdate(_a0 context.Context, _a1 *domain.Buy) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for BuyUpdate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Buy) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ConfigGet provides a mock function with given fields: _a0
func (_m *DbRepository) ConfigGet(_a0 context.Context) (*domain.Config, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for ConfigGet")
	}

	var r0 *domain.Config
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*domain.Config, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *domain.Config); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Config)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PlanGetByCode provides a mock function with given fields: _a0, _a1
func (_m *DbRepository) PlanGetByCode(_a0 context.Context, _a1 string) (*domain.Plan, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for PlanGetByCode")
	}

	var r0 *domain.Plan
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Plan, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Plan); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Plan)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ProductGetByCode provides a mock function with given fields: _a0, _a1
func (_m *DbRepository) ProductGetByCode(_a0 context.Context, _a1 string) (*domain.Product, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for ProductGetByCode")
	}

	var r0 *domain.Product
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Product, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Product); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Product)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ProductIncCount provides a mock function with given fields: _a0, _a1
func (_m *DbRepository) ProductIncCount(_a0 context.Context, _a1 string) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for ProductIncCount")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RankGetByCode provides a mock function with given fields: _a0, _a1
func (_m *DbRepository) RankGetByCode(_a0 context.Context, _a1 string) (*domain.Rank, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for RankGetByCode")
	}

	var r0 *domain.Rank
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Rank, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Rank); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Rank)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TransactionCreate provides a mock function with given fields: _a0, _a1
func (_m *DbRepository) TransactionCreate(_a0 context.Context, _a1 *domain.Transaction) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for TransactionCreate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Transaction) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UserActivityGet provides a mock function with given fields: _a0, _a1
func (_m *DbRepository) UserActivityGet(_a0 context.Context, _a1 string) (*domain.UserActivity, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for UserActivityGet")
	}

	var r0 *domain.UserActivity
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.UserActivity, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.UserActivity); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.UserActivity)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserBalanceChange provides a mock function with given fields: _a0, _a1, _a2, _a3, _a4
func (_m *DbRepository) UserBalanceChange(_a0 context.Context, _a1 string, _a2 string, _a3 uint8, _a4 int64) error {
	ret := _m.Called(_a0, _a1, _a2, _a3, _a4)

	if len(ret) == 0 {
		panic("no return value specified for UserBalanceChange")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, uint8, int64) error); ok {
		r0 = rf(_a0, _a1, _a2, _a3, _a4)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UserBalanceGetByUserUIDAndCurrencyCode provides a mock function with given fields: _a0, _a1, _a2
func (_m *DbRepository) UserBalanceGetByUserUIDAndCurrencyCode(_a0 context.Context, _a1 string, _a2 string) (*domain.UserBalance, error) {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for UserBalanceGetByUserUIDAndCurrencyCode")
	}

	var r0 *domain.UserBalance
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*domain.UserBalance, error)); ok {
		return rf(_a0, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *domain.UserBalance); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.UserBalance)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserClaimCreate provides a mock function with given fields: _a0, _a1
func (_m *DbRepository) UserClaimCreate(_a0 context.Context, _a1 *domain.UserClaim) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for UserClaimCreate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.UserClaim) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UserGetAllUpByUID provides a mock function with given fields: _a0, _a1, _a2
func (_m *DbRepository) UserGetAllUpByUID(_a0 context.Context, _a1 string, _a2 int) ([]*domain.User, error) {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for UserGetAllUpByUID")
	}

	var r0 []*domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int) ([]*domain.User, error)); ok {
		return rf(_a0, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int) []*domain.User); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int) error); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserGetByUID provides a mock function with given fields: _a0, _a1
func (_m *DbRepository) UserGetByUID(_a0 context.Context, _a1 string) (*domain.User, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for UserGetByUID")
	}

	var r0 *domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.User, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.User); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserPlaceGetByUserUID provides a mock function with given fields: _a0, _a1
func (_m *DbRepository) UserPlaceGetByUserUID(_a0 context.Context, _a1 string) (*domain.UserPlace, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for UserPlaceGetByUserUID")
	}

	var r0 *domain.UserPlace
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.UserPlace, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.UserPlace); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.UserPlace)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserPlanCreate provides a mock function with given fields: _a0, _a1
func (_m *DbRepository) UserPlanCreate(_a0 context.Context, _a1 *domain.UserPlan) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for UserPlanCreate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.UserPlan) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UserPlanGetByCodeAndDate provides a mock function with given fields: _a0, _a1, _a2, _a3
func (_m *DbRepository) UserPlanGetByCodeAndDate(_a0 context.Context, _a1 string, _a2 string, _a3 time.Time) (*domain.UserPlan, error) {
	ret := _m.Called(_a0, _a1, _a2, _a3)

	if len(ret) == 0 {
		panic("no return value specified for UserPlanGetByCodeAndDate")
	}

	var r0 *domain.UserPlan
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, time.Time) (*domain.UserPlan, error)); ok {
		return rf(_a0, _a1, _a2, _a3)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, time.Time) *domain.UserPlan); ok {
		r0 = rf(_a0, _a1, _a2, _a3)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.UserPlan)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, time.Time) error); ok {
		r1 = rf(_a0, _a1, _a2, _a3)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserPlanGetByDate provides a mock function with given fields: _a0, _a1, _a2
func (_m *DbRepository) UserPlanGetByDate(_a0 context.Context, _a1 string, _a2 time.Time) (*domain.UserPlan, error) {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for UserPlanGetByDate")
	}

	var r0 *domain.UserPlan
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time) (*domain.UserPlan, error)); ok {
		return rf(_a0, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time) *domain.UserPlan); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.UserPlan)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, time.Time) error); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserPlanGetByUID provides a mock function with given fields: _a0, _a1
func (_m *DbRepository) UserPlanGetByUID(_a0 context.Context, _a1 string) (*domain.UserPlan, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for UserPlanGetByUID")
	}

	var r0 *domain.UserPlan
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.UserPlan, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.UserPlan); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.UserPlan)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserPlanGetLastByCodeAndDate provides a mock function with given fields: _a0, _a1, _a2, _a3
func (_m *DbRepository) UserPlanGetLastByCodeAndDate(_a0 context.Context, _a1 string, _a2 string, _a3 time.Time) (*domain.UserPlan, error) {
	ret := _m.Called(_a0, _a1, _a2, _a3)

	if len(ret) == 0 {
		panic("no return value specified for UserPlanGetLastByCodeAndDate")
	}

	var r0 *domain.UserPlan
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, time.Time) (*domain.UserPlan, error)); ok {
		return rf(_a0, _a1, _a2, _a3)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, time.Time) *domain.UserPlan); ok {
		r0 = rf(_a0, _a1, _a2, _a3)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.UserPlan)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, time.Time) error); ok {
		r1 = rf(_a0, _a1, _a2, _a3)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserPlanUpdate provides a mock function with given fields: _a0, _a1
func (_m *DbRepository) UserPlanUpdate(_a0 context.Context, _a1 *domain.UserPlan) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for UserPlanUpdate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.UserPlan) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UserProductCreate provides a mock function with given fields: _a0, _a1
func (_m *DbRepository) UserProductCreate(_a0 context.Context, _a1 *domain.UserProduct) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for UserProductCreate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.UserProduct) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UserProductGetByCategoryAndDate provides a mock function with given fields: _a0, _a1, _a2, _a3
func (_m *DbRepository) UserProductGetByCategoryAndDate(_a0 context.Context, _a1 string, _a2 string, _a3 time.Time) (*domain.UserProduct, error) {
	ret := _m.Called(_a0, _a1, _a2, _a3)

	if len(ret) == 0 {
		panic("no return value specified for UserProductGetByCategoryAndDate")
	}

	var r0 *domain.UserProduct
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, time.Time) (*domain.UserProduct, error)); ok {
		return rf(_a0, _a1, _a2, _a3)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, time.Time) *domain.UserProduct); ok {
		r0 = rf(_a0, _a1, _a2, _a3)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.UserProduct)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, time.Time) error); ok {
		r1 = rf(_a0, _a1, _a2, _a3)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserProductGetByCode provides a mock function with given fields: _a0, _a1, _a2
func (_m *DbRepository) UserProductGetByCode(_a0 context.Context, _a1 string, _a2 string) (*domain.UserProduct, error) {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for UserProductGetByCode")
	}

	var r0 *domain.UserProduct
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*domain.UserProduct, error)); ok {
		return rf(_a0, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *domain.UserProduct); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.UserProduct)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserProductGetByCodeAndDate provides a mock function with given fields: _a0, _a1, _a2, _a3
func (_m *DbRepository) UserProductGetByCodeAndDate(_a0 context.Context, _a1 string, _a2 string, _a3 time.Time) (*domain.UserProduct, error) {
	ret := _m.Called(_a0, _a1, _a2, _a3)

	if len(ret) == 0 {
		panic("no return value specified for UserProductGetByCodeAndDate")
	}

	var r0 *domain.UserProduct
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, time.Time) (*domain.UserProduct, error)); ok {
		return rf(_a0, _a1, _a2, _a3)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, time.Time) *domain.UserProduct); ok {
		r0 = rf(_a0, _a1, _a2, _a3)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.UserProduct)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, time.Time) error); ok {
		r1 = rf(_a0, _a1, _a2, _a3)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserProductGetLastByCategoryAndDate provides a mock function with given fields: _a0, _a1, _a2, _a3
func (_m *DbRepository) UserProductGetLastByCategoryAndDate(_a0 context.Context, _a1 string, _a2 string, _a3 time.Time) (*domain.UserProduct, error) {
	ret := _m.Called(_a0, _a1, _a2, _a3)

	if len(ret) == 0 {
		panic("no return value specified for UserProductGetLastByCategoryAndDate")
	}

	var r0 *domain.UserProduct
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, time.Time) (*domain.UserProduct, error)); ok {
		return rf(_a0, _a1, _a2, _a3)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, time.Time) *domain.UserProduct); ok {
		r0 = rf(_a0, _a1, _a2, _a3)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.UserProduct)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, time.Time) error); ok {
		r1 = rf(_a0, _a1, _a2, _a3)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserProductUpdate provides a mock function with given fields: _a0, _a1
func (_m *DbRepository) UserProductUpdate(_a0 context.Context, _a1 *domain.UserProduct) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for UserProductUpdate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.UserProduct) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UserRankCreate provides a mock function with given fields: _a0, _a1
func (_m *DbRepository) UserRankCreate(_a0 context.Context, _a1 *domain.UserRank) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for UserRankCreate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.UserRank) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UserRankGetByCodeAndDate provides a mock function with given fields: _a0, _a1, _a2, _a3
func (_m *DbRepository) UserRankGetByCodeAndDate(_a0 context.Context, _a1 string, _a2 string, _a3 time.Time) (*domain.UserRank, error) {
	ret := _m.Called(_a0, _a1, _a2, _a3)

	if len(ret) == 0 {
		panic("no return value specified for UserRankGetByCodeAndDate")
	}

	var r0 *domain.UserRank
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, time.Time) (*domain.UserRank, error)); ok {
		return rf(_a0, _a1, _a2, _a3)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, time.Time) *domain.UserRank); ok {
		r0 = rf(_a0, _a1, _a2, _a3)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.UserRank)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, time.Time) error); ok {
		r1 = rf(_a0, _a1, _a2, _a3)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserRankGetByUID provides a mock function with given fields: _a0, _a1
func (_m *DbRepository) UserRankGetByUID(_a0 context.Context, _a1 string) (*domain.UserRank, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for UserRankGetByUID")
	}

	var r0 *domain.UserRank
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.UserRank, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.UserRank); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.UserRank)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserRankUpdate provides a mock function with given fields: _a0, _a1
func (_m *DbRepository) UserRankUpdate(_a0 context.Context, _a1 *domain.UserRank) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for UserRankUpdate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.UserRank) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UserSafeGetActiveBySafeUIDsAndUserUID provides a mock function with given fields: _a0, _a1, _a2
func (_m *DbRepository) UserSafeGetActiveBySafeUIDsAndUserUID(_a0 context.Context, _a1 []string, _a2 string) (*domain.UserSafe, error) {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for UserSafeGetActiveBySafeUIDsAndUserUID")
	}

	var r0 *domain.UserSafe
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []string, string) (*domain.UserSafe, error)); ok {
		return rf(_a0, _a1, _a2)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []string, string) *domain.UserSafe); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.UserSafe)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []string, string) error); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserSafeUpdate provides a mock function with given fields: _a0, _a1
func (_m *DbRepository) UserSafeUpdate(_a0 context.Context, _a1 *domain.UserSafe) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for UserSafeUpdate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.UserSafe) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewDbRepository creates a new instance of DbRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDbRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *DbRepository {
	mock := &DbRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
