// Code generated by mockery v2.38.0. DO NOT EDIT.

package mocks

import (
	context "context"
	domain "server/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// WfRepository is an autogenerated mock type for the WfRepository type
type WfRepository struct {
	mock.Mock
}

// AutofarmCreate provides a mock function with given fields: _a0, _a1
func (_m *WfRepository) AutofarmCreate(_a0 context.Context, _a1 *domain.UserProduct) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for AutofarmCreate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.UserProduct) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// BuyCreate provides a mock function with given fields: _a0, _a1
func (_m *WfRepository) BuyCreate(_a0 context.Context, _a1 *domain.Buy) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for BuyCreate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Buy) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// BuyProduct provides a mock function with given fields: _a0, _a1
func (_m *WfRepository) BuyProduct(_a0 context.Context, _a1 *domain.Buy) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for BuyProduct")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Buy) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// BuySignalPaid provides a mock function with given fields: _a0, _a1, _a2
func (_m *WfRepository) BuySignalPaid(_a0 context.Context, _a1 *domain.Buy, _a2 *domain.BuySignalPaid) error {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for BuySignalPaid")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Buy, *domain.BuySignalPaid) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// BuySignalRefund provides a mock function with given fields: _a0, _a1, _a2
func (_m *WfRepository) BuySignalRefund(_a0 context.Context, _a1 *domain.Buy, _a2 *domain.BuySignalRefund) error {
	ret := _m.Called(_a0, _a1, _a2)

	if len(ret) == 0 {
		panic("no return value specified for BuySignalRefund")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Buy, *domain.BuySignalRefund) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewWfRepository creates a new instance of WfRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWfRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *WfRepository {
	mock := &WfRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
